(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var k=this||self,aa=function(a){return a};var ba=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};var ca,n;a:{for(var da=["CLOSURE_FLAGS"],q=k,ea=0;ea<da.length;ea++)if(q=q[da[ea]],null==q){n=null;break a}n=q}var fa=n&&n[610401301];ca=null!=fa?fa:!1;var r;const ha=k.navigator;r=ha?ha.userAgentData||null:null;function ia(a){return ca?r?r.brands.some(({brand:b})=>b&&-1!=b.indexOf(a)):!1:!1}function t(a){var b;a:{if(b=k.navigator)if(b=b.userAgent)break a;b=""}return-1!=b.indexOf(a)};function u(){return ca?!!r&&0<r.brands.length:!1}function ja(){return u()?ia("Chromium"):(t("Chrome")||t("CriOS"))&&!(u()?0:t("Edge"))||t("Silk")};var ka=u()?!1:t("Trident")||t("MSIE");!t("Android")||ja();ja();t("Safari")&&(ja()||(u()?0:t("Coast"))||(u()?0:t("Opera"))||(u()?0:t("Edge"))||(u()?ia("Microsoft Edge"):t("Edg/"))||u()&&ia("Opera"));var la={},v=null;var ma="undefined"!==typeof Uint8Array,na=!ka&&"function"===typeof btoa;var w;w="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol():void 0;var oa=w?(a,b)=>{a[w]|=b}:(a,b)=>{void 0!==a.g?a.g|=b:Object.defineProperties(a,{g:{value:b,configurable:!0,writable:!0,enumerable:!1}})};function x(a,b,c){return c?a|b:a&~b}var y=w?a=>a[w]|0:a=>a.g|0,A=w?a=>a[w]:a=>a.g,B=w?(a,b)=>{a[w]=b;return a}:(a,b)=>{void 0!==a.g?a.g=b:Object.defineProperties(a,{g:{value:b,configurable:!0,writable:!0,enumerable:!1}});return a};function pa(a,b){B(b,(a|0)&-14591)}function ta(a,b){B(b,(a|34)&-14557)}function ua(a){a=a>>14&1023;return 0===a?536870912:a};var D={},va={};function wa(a){return!(!a||"object"!==typeof a||a.g!==va)}function xa(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}let ya;function E(a,b,c){if(!Array.isArray(a)||a.length)return!1;const d=y(a);if(d&1)return!0;if(!(b&&(Array.isArray(b)?b.includes(c):b.has(c))))return!1;B(a,d|1);return!0}var za;const Aa=[];B(Aa,55);za=Object.freeze(Aa);class Ba{}class Ca{}Object.freeze(new Ba);Object.freeze(new Ca);function Da(a){if(null==a)return a;if("string"===typeof a){if(!a)return;a=+a}if("number"===typeof a)return Number.isFinite(a)?a|0:void 0}function Ea(a,b,c){if(null!=a&&"object"===typeof a&&a.i===D)return a;if(Array.isArray(a)){var d=y(a),g=d;0===g&&(g|=c&32);g|=c&2;g!==d&&B(a,g);return new b(a)}};let F;function Fa(a,b){F=b;a=new a(b);F=void 0;return a};function Ga(a,b){return Ha(b)}
function Ha(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "boolean":return a?1:0;case "object":if(a)if(Array.isArray(a)){if(E(a,void 0,0))return}else if(ma&&null!=a&&a instanceof Uint8Array){if(na){for(var b="",c=0,d=a.length-10240;c<d;)b+=String.fromCharCode.apply(null,a.subarray(c,c+=10240));b+=String.fromCharCode.apply(null,c?a.subarray(c):a);a=btoa(b)}else{void 0===b&&(b=0);if(!v){v={};c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split("");d=["+/=",
"+/","-_=","-_.","-_"];for(var g=0;5>g;g++){var e=c.concat(d[g].split(""));la[g]=e;for(var h=0;h<e.length;h++){var f=e[h];void 0===v[f]&&(v[f]=h)}}}b=la[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(g=e=0;e<a.length-2;e+=3){var m=a[e],l=a[e+1];f=a[e+2];h=b[m>>2];m=b[(m&3)<<4|l>>4];l=b[(l&15)<<2|f>>6];f=b[f&63];c[g++]=""+h+m+l+f}h=0;f=d;switch(a.length-e){case 2:h=a[e+1],f=b[(h&15)<<2]||d;case 1:a=a[e],c[g]=""+b[a>>2]+b[(a&3)<<4|h>>4]+f+d}a=c.join("")}return a}}return a};function Ia(a,b,c){a=Array.prototype.slice.call(a);var d=a.length;const g=b&256?a[d-1]:void 0;d+=g?-1:0;for(b=b&512?1:0;b<d;b++)a[b]=c(a[b]);if(g){b=a[b]={};for(const e in g)b[e]=c(g[e])}return a}function Ja(a,b,c,d,g){if(null!=a){if(Array.isArray(a))a=E(a,void 0,0)?void 0:g&&y(a)&2?a:Ka(a,b,c,void 0!==d,g);else if(xa(a)){const e={};for(let h in a)e[h]=Ja(a[h],b,c,d,g);a=e}else a=b(a,d);return a}}
function Ka(a,b,c,d,g){const e=d||c?y(a):0;d=d?!!(e&32):void 0;a=Array.prototype.slice.call(a);for(let h=0;h<a.length;h++)a[h]=Ja(a[h],b,c,d,g);c&&c(e,a);return a}function La(a){return a.i===D?a.toJSON():Ha(a)};function Ma(a,b,c=ta){if(null!=a){if(ma&&a instanceof Uint8Array)return b?a:new Uint8Array(a);if(Array.isArray(a)){var d=y(a);if(d&2)return a;b&&(b=0===d||!!(d&32)&&!(d&64||!(d&16)));return b?B(a,(d|34)&-12293):Ka(a,Ma,d&4?ta:c,!0,!0)}a.i===D&&(c=a.h,d=A(c),a=d&2?a:Fa(a.constructor,Na(c,d,!0)));return a}}function Na(a,b,c){const d=c||b&2?ta:pa,g=!!(b&32);a=Ia(a,b,e=>Ma(e,g,d));oa(a,32|(c?2:0));return a}function Oa(a){const b=a.h,c=A(b);return c&2?Fa(a.constructor,Na(b,c,!1)):a};var Pa=function(a,b){a=a.h;return G(a,A(a),b)},G=function(a,b,c,d){if(-1===c)return null;if(c>=ua(b)){if(b&256)return a[a.length-1][c]}else{var g=a.length;if(d&&b&256&&(d=a[g-1][c],null!=d))return d;b=c+(+!!(b&512)-1);if(b<g)return a[b]}};
function H(a,b,c,d,g){const e=ua(b);if(c>=e||g){let h=b;if(b&256)g=a[a.length-1];else{if(null==d)return h;g=a[e+(+!!(b&512)-1)]={};h|=256}g[c]=d;c<e&&(a[c+(+!!(b&512)-1)]=void 0);h!==b&&B(a,h);return h}a[c+(+!!(b&512)-1)]=d;b&256&&(a=a[a.length-1],c in a&&delete a[c]);return b}var L=function(a,b,c){return void 0!==I(a,b,J(a,K,c))},Qa=function(a,b){a=Pa(a,b);return null==a||"boolean"===typeof a?a:"number"===typeof a?!!a:void 0};function Sa(a){return!!(2&a)&&!!(4&a)||!!(2048&a)}
function Ta(a,b,c,d){const g=a.h;let e=A(g);if(e&2)throw Error();H(g,e,b,("0"===d?0===Number(c):c===d)?void 0:c);return a}var J=function(a,b,c){a=a.h;return Ua(a,A(a),b)===c?c:-1};function Ua(a,b,c){let d=0;for(let g=0;g<c.length;g++){const e=c[g];null!=G(a,b,e)&&(0!==d&&(b=H(a,b,d)),d=e)}return d}function I(a,b,c,d){a=a.h;let g=A(a);const e=G(a,g,c,d);b=Ea(e,b,g);b!==e&&null!=b&&H(a,g,c,b,d);return b}
var M=function(a,b,c){b=I(a,b,c,!1);if(null==b)return b;a=a.h;let d=A(a);if(!(d&2)){const g=Oa(b);g!==b&&(b=g,H(a,d,c,b,!1))}return b},Xa=function(a,b){a=a.h;var c=A(a),d=c,g=!(2&c),e=!!(2&d),h=e?1:2;c=1===h;h=2===h;g&&(g=!e);e=G(a,d,b);e=Array.isArray(e)?e:za;var f=y(e);const m=!!(4&f);if(!m){var l=f;0===l&&(l=Va(l,d));l=x(l,1,!0);f=e;var z=d,C=Wa;const p=!!(2&l);p&&(z=x(z,2,!0));let N=!p,qa=!0,W=0,ra=0;for(;W<f.length;W++){const sa=Ea(f[W],C,z);if(sa instanceof C){if(!p){const Ra=!!(y(sa.h)&2);
N&&(N=!Ra);qa&&(qa=Ra)}f[ra++]=sa}}ra<W&&(f.length=ra);l=x(l,4,!0);l=x(l,16,qa);l=x(l,8,N);B(f,l);p&&Object.freeze(f);f=l}l=!!(8&f)||c&&!e.length;if(g&&!l){Sa(f)&&(e=Array.prototype.slice.call(e),f=Va(f,d),d=H(a,d,b,e));g=e;for(l=0;l<g.length;l++)z=g[l],C=Oa(z),z!==C&&(g[l]=C);f=x(f,8,!0);f=x(f,16,!g.length);B(g,f)}Sa(f)||(g=f,c?f=x(f,!e.length||16&f&&(!m||32&f)?2:2048,!0):f=x(f,32,!1),f!==g&&B(e,f),c&&Object.freeze(e));h&&Sa(f)&&(e=Array.prototype.slice.call(e),f=Va(f,d),B(e,f),H(a,d,b,e));return e};
function Va(a,b){a=x(a,2,!!(2&b));a=x(a,32,!!(32&b)&&!1);return a=x(a,2048,!1)}var O=function(a,b){a=Qa(a,b);return null!=a?a:!1},P=function(a,b){a=Da(Pa(a,b));return null!=a?a:0},Q=function(a,b){a=Pa(a,b);a=null==a||"string"===typeof a?a:void 0;return null!=a?a:""};var R=class{constructor(a){a:{null==a&&(a=F);F=void 0;if(null==a){var b=96;a=[]}else{if(!Array.isArray(a))throw Error();b=y(a);if(b&64)break a;var c=a;b|=64;var d=c.length;if(d&&(--d,xa(c[d]))){b|=256;c=d-(+!!(b&512)-1);if(1024<=c)throw Error();b=b&-16760833|(c&1023)<<14}}B(a,b)}this.h=a}toJSON(){return ya?Ya(this,this.h,!1):Ya(this,Ka(this.h,La,void 0,void 0,!1),!0)}};R.prototype.i=D;R.prototype.toString=function(){return Ya(this,this.h,!1).toString()};
function Ya(a,b,c){const d=a.constructor.j,g=A(c?a.h:b);a=b.length;if(!a)return b;let e,h;if(xa(c=b[a-1])){a:{var f=c;let z={},C=!1;for(var m in f){let p=f[m];if(Array.isArray(p)){let N=p;if(E(p,d,+m)||wa(p)&&0===p.size)p=null;p!=N&&(C=!0)}null!=p?z[m]=p:C=!0}if(C){for(var l in z){f=z;break a}f=null}}f!=c&&(e=!0);a--}for(m=+!!(g&512)-1;0<a;a--){l=a-1;c=b[l];l-=m;if(!(null==c||E(c,d,l)||wa(c)&&0===c.size))break;h=!0}if(!e&&!h)return b;b=Array.prototype.slice.call(b,0,a);f&&b.push(f);return b};var Wa=class extends R{},S=[2,3,4];var T=class extends R{};var U=class extends R{};var Za=class extends R{};Za.j=[6];var $a=class extends R{constructor(){super()}};var ab=class extends R{constructor(){super()}},bb=[2];var cb=class extends R{};cb.j=[2];var db=class extends R{};var eb=class extends R{};var fb=class extends R{};var gb=function(a){return b=>{if(null==b||""==b)b=new a;else{b=JSON.parse(b);if(!Array.isArray(b))throw Error(void 0);oa(b,32);b=Fa(a,b)}return b}}(class extends R{}),K=[2,3,4,5,6,7];var V;var hb=class{constructor(a){this.g=a}toString(){return this.g+""}},ib={},jb=function(a){if(void 0===V){var b=null;var c=k.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:aa,createScript:aa,createScriptURL:aa})}catch(d){k.console&&k.console.error(d.message)}V=b}else V=b}a=(b=V)?b.createScriptURL(a):a;return new hb(a,ib)};var kb=function(){this.g=document||{cookie:""}};
kb.prototype.set=function(a,b,c){let d,g,e,h=!1,f;"object"===typeof c&&(f=c.u,h=c.v||!1,e=c.domain||void 0,g=c.path||void 0,d=c.o);if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');void 0===d&&(d=-1);this.g.cookie=a+"="+b+(e?";domain="+e:"")+(g?";path="+g:"")+(0>d?"":0==d?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(Date.now()+1E3*d)).toUTCString())+(h?";secure":"")+(null!=f?";samesite="+f:"")};
kb.prototype.get=function(a,b){const c=a+"=",d=(this.g.cookie||"").split(";");for(let g=0,e;g<d.length;g++){e=ba(d[g]);if(0==e.lastIndexOf(c,0))return e.slice(c.length);if(e==a)return""}return b};
kb.prototype.clear=function(){var a=(this.g.cookie||"").split(";");const b=[];var c=[];let d,g;for(let e=0;e<a.length;e++)g=ba(a[e]),d=g.indexOf("="),-1==d?(b.push(""),c.push(g)):(b.push(g.substring(0,d)),c.push(g.substring(d+1)));for(c=b.length-1;0<=c;c--)a=b[c],this.get(a),this.set(a,"",{o:0,path:void 0,domain:void 0})};/*

 SPDX-License-Identifier: Apache-2.0
*/
function lb(a,...b){if(0===b.length)return jb(a[0]);let c=a[0];for(let d=0;d<b.length;d++)c+=encodeURIComponent(b[d])+a[d+1];return jb(c)};class mb{constructor(){this.l=new kb;this.g="";this.m=a=>{a:{let m;try{m=gb(a.data)}catch(l){break a}if(L(m,Za,4)){var b=M(m,Za,J(m,K,4));var c=Xa(b,6);var d;c.length&&(d=nb(c));c={event:Q(b,1)||void 0,category:Q(b,2)||void 0,action:Q(b,3)||void 0,label:Q(b,4)||void 0,value:P(b,5)||void 0,nonInteraction:O(b,13)?"True":"False",additionalParams:d||void 0};if(void 0!==I(b,U,12,!1)){var g=M(b,U,12);c.recommendations={targetPage:Q(g,1),targetType:P(g,2),targetRank:P(g,3),targetIdenticalDescriptions:P(g,
4),targetTitleWords:P(g,5),targetDescriptionWords:P(g,6),experiment:Q(g,7)};d="";for(var e of window.dataLayer)if("experiment"in e&&"baseIds"in e.experiment){d=e.experiment.baseIds;break}(d=ob(d,Q(g,7)))&&O(g,8)&&(c.experiment={ids:d})}else c.recommendations={targetPage:void 0,targetType:void 0,targetRank:void 0,targetIdenticalDescriptions:void 0,targetTitleWords:void 0,targetDescriptionWords:void 0};if(!("experiment"in c))for(var h of window.dataLayer)if("experiment"in h&&"ids"in h.experiment&&h.experiment.ids){c.experiment=
{ids:h.experiment.ids};break}e=M(b,T,11);if(void 0!==I(b,T,11,!1)&&null!==e){e=pb(e);for(var f of Object.keys(e))c[f]=e[f]}window.dataLayer.push(c)}else if(L(m,cb,3)){f=M(m,cb,J(m,K,3));e=Xa(f,2);let l;e.length&&(l=nb(e));e={event:"trackPageview",pageName:Q(f,1),additionalParams:l||void 0,nonInteraction:O(f,3)||void 0,ratingsCount:P(f,4)||void 0,ratingsValue:P(f,5)||void 0};h=M(f,T,6);if(void 0!==I(f,T,6,!1)&&null!==h){f=pb(h);for(b of Object.keys(f))e[b]=f[b]}window.dataLayer.push(e)}else L(m,db,
7)?(f=M(m,db,J(m,K,7)),window.dataLayer.push({parentContext:{referrer:Q(f,2)||"",_ga_devsiteCookie:Q(f,1)||""}})):L(m,eb,6)?(f=M(m,eb,J(m,K,6)),e=this.g,h=M(f,U,9)||new U,b=Q(f,10)||void 0,f={experiment:{ids:(O(h,8)?ob(b,Q(h,7)):b)||void 0,baseIds:b||void 0},hostContext:{internalUser:Q(f,1)||void 0,pageType:Q(f,8)||void 0,projectName:Q(f,6)||void 0,signedIn:Q(f,2)||void 0,tenant:Q(f,5)||void 0,thirdPartyCookieAccepted:e.length?"True":"False"},language:{machineTranslated:Q(f,7)||void 0,requested:Q(f,
3)||void 0,served:Q(f,4)||void 0},recommendations:{sourcePage:Q(h,1),sourceType:P(h,2),sourceRank:P(h,3),sourceIdenticalDescriptions:P(h,4),sourceTitleWords:P(h,5),sourceDescriptionWords:P(h,6),experiment:Q(h,7)}},window.dataLayer.push(f)):L(m,fb,5)?(f=M(m,fb,J(m,K,5)),window.dataLayer.push({originalUrlParameters:{dclid:Q(f,1)||void 0,gclid:Q(f,2)||void 0,utmCampaign:Q(f,3)||void 0,utmContent:Q(f,4)||void 0,utmCreativeFormat:Q(f,8)||void 0,utmMarketingTactic:Q(f,10)||void 0,utmMedium:Q(f,5)||void 0,
utmSource:Q(f,6)||void 0,utmSourcePlatform:Q(f,9)||void 0,utmTerm:Q(f,7)||void 0}})):null!=Qa(m,J(m,K,2))&&(window.dataLayer=window.dataLayer||[],window.dataLayer.push({"gtm.start":(new Date).getTime(),event:"gtm.js"}),e=document,f=e.getElementsByTagName("script")[0],e=e.createElement("script"),e.async=!0,h=lb`//www.googletagmanager.com/gtm.js?id=GTM-PBZPJDG`,e.src=h instanceof hb&&h.constructor===hb?h.g:"type_error:TrustedResourceUrl",(h=(h=null==(g=(c=(e.ownerDocument&&e.ownerDocument.defaultView||
window).document).querySelector)?void 0:g.call(c,"script[nonce]"))?h.nonce||h.getAttribute("nonce")||"":"")&&e.setAttribute("nonce",h),f.parentNode.insertBefore(e,f))}};window.addEventListener("message",this.m)}s(a){this.g=this.l.get("_ga_devsite")||"";var b=new $a;if(null!=a&&"boolean"!==typeof a){var c=typeof a;throw Error(`Expected boolean but got ${"object"!=c?c:a?Array.isArray(a)?"array":c:"null"}: ${a}`);}a=Ta(b,1,a,!1);b=this.g;if(null!=b&&"string"!==typeof b)throw Error();b=Ta(a,2,b,"");a=
new ab;null==b&&(b=void 0);var d=a.h;let g=A(d);if(g&2)throw Error();let e=Ua(d,g,bb);e&&2!==e&&null!=b&&(g=H(d,g,e));H(d,g,2,b);if(window.parent!==window){b=window.parent;d=b.postMessage;a:{ya=!0;try{c=JSON.stringify(a.toJSON(),Ga);break a}finally{ya=!1}c=void 0}d.call(b,c,"*")}}}mb.prototype.notifyIframeReady=mb.prototype.s;
function nb(a){const b={};for(const c of a){a=Q(c,1);let d;Q(c,J(c,S,2))?d=Q(c,J(c,S,2)):P(c,J(c,S,3))?d=P(c,J(c,S,3)):null!=Qa(c,J(c,S,4))&&(d=O(c,J(c,S,4))?"True":"False");b[a]=d}return b}
function pb(a){const b={};if(!a)return b;b.hasProfile=O(a,6)?"True":"False";b.practitionerType=Q(a,1)||"Property not set";b.profileCreationMethod=Q(a,4)||"Property not set";b.profileHasInterests=O(a,12)?"True":"False";b.profileInterests=Q(a,13)||"Property not set";b.profileHasJobTitle=O(a,10)?"True":"False";b.profileHasLocation=O(a,7)?"True":"False";b.profileHasPronoun=O(a,9)?"True":"False";b.profileIsPublic=O(a,8)?"True":"False";b.profileSocialLinks=Q(a,11)||"Property not set";b.profileBadgeEmailOptIn=
O(a,5)?"True":"False";b.profileFeedbackEmailOptIn=O(a,2)?"True":"False";b.profileNewsletterEmailOptIn=O(a,3)?"True":"False";return b}function ob(a,b){if(a||b){if(a&&!b)return a;if(b&&!a)return b;b=new Set(b.split(","));a=[...(new Set([...(new Set(a.split(","))),...b]))];a.sort();return a.join(",")}}var qb=mb,X=["AnalyticsLibrary"],Y=k;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);
for(var Z;X.length&&(Z=X.shift());)X.length||void 0===qb?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=qb;}).call(this);
