(function(){var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},ca=ba(this),fa=function(a,b){if(b)a:{var c=ca;a=a.split(".");for(var e=0;e<
a.length-1;e++){var h=a[e];if(!(h in c))break a;c=c[h]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}};
fa("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var d=this||self,m=function(a,b){a=a.split(".");var c=d;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var e;a.length&&(e=a.shift());)a.length||void 0===b?c[e]&&c[e]!==Object.prototype[e]?c=c[e]:c=c[e]={}:c[e]=b},n=function(a){return a};var q=new Map([]);q.set("devsite-a11y-announce",{src:"/developers/js/devsite_devsite_a11y_announce_module.js"});q.set("devsite-analytics",{src:"/developers/js/devsite_devsite_analytics_module.js"});q.set("devsite-analytics-scope",{src:"/developers/js/devsite_devsite_analytics_scope_module.js"});q.set("devsite-anselm",{src:"/developers/js/devsite_devsite_anselm_module.js"});q.set("devsite-api-getstarted",{src:"/developers/js/devsite_devsite_api_getstarted_module.js"});q.set("devsite-apix",{src:"/developers/js/devsite_devsite_apix_module.js"});
q.set("devsite-apix-index",{src:"/developers/js/devsite_devsite_apix_index_module.js"});q.set("devsite-apix-snippets",{src:"/developers/js/devsite_devsite_apix_snippets_module.js"});q.set("devsite-appearance-selector",{src:"/developers/js/devsite_devsite_appearance_selector_module.js"});q.set("devsite-author-page-insights",{src:"/developers/js/devsite_devsite_author_page_insights_module.js"});q.set("devsite-badge-awarded",{src:"/developers/js/devsite_devsite_badge_awarded_module.js"});
q.set("devsite-badge-awarder",{src:"/developers/js/devsite_devsite_badge_awarder_module.js"});q.set("devsite-badge-redeemer",{src:"/developers/js/devsite_devsite_badge_redeemer_module.js"});q.set("devsite-badger",{src:"/developers/js/devsite_devsite_badger_module.js"});q.set("devsite-book-nav",{src:"/developers/js/devsite_devsite_book_nav_module.js"});q.set("devsite-bookmark",{src:"/developers/js/devsite_devsite_bookmark_module.js"});q.set("devsite-carousel",{src:"/developers/js/devsite_devsite_carousel_module.js"});
q.set("devsite-catalog",{src:"/developers/js/devsite_devsite_catalog_module.js"});q.set("devsite-catalog-body-badges",{src:"/developers/js/devsite_devsite_catalog_body_badges_module.js"});q.set("devsite-chart",{src:"/developers/js/devsite_devsite_chart_module.js"});q.set("devsite-checkbox",{src:"/developers/js/devsite_devsite_checkbox_module.js"});q.set("devsite-code",{src:"/developers/js/devsite_devsite_code_module.js"});q.set("devsite-codelab-catalog",{src:"/developers/js/devsite_devsite_codelab_catalog_module.js"});
q.set("devsite-concierge",{src:"/developers/js/devsite_devsite_concierge_module.js"});q.set("devsite-concierge-ai-panel",{src:"/developers/js/devsite_devsite_concierge_ai_panel_module.js"});q.set("devsite-concierge-api-explorer-panel",{src:"/developers/js/devsite_devsite_concierge_api_explorer_panel_module.js"});q.set("devsite-concierge-apix",{src:"/developers/js/devsite_devsite_concierge_apix_module.js"});q.set("devsite-concierge-info-panel",{src:"/developers/js/devsite_devsite_concierge_info_panel_module.js"});
q.set("devsite-concierge-my-activity-panel",{src:"/developers/js/devsite_devsite_concierge_my_activity_panel_module.js"});q.set("devsite-concierge-recommendations-panel",{src:"/developers/js/devsite_devsite_concierge_recommendations_panel_module.js"});q.set("devsite-content",{src:"/developers/js/devsite_devsite_content_module.js"});q.set("devsite-content-excellence",{src:"/developers/js/devsite_devsite_content_excellence_module.js"});q.set("devsite-cookie-consent",{src:"/developers/js/devsite_devsite_cookie_consent_module.js"});
q.set("devsite-cookie-notification-bar",{src:"/developers/js/devsite_devsite_cookie_notification_bar_module.js"});q.set("devsite-countdown",{src:"/developers/js/devsite_devsite_countdown_module.js"});q.set("devsite-credentials-dialog",{src:"/developers/js/devsite_devsite_credentials_dialog_module.js"});q.set("devsite-cse",{src:"/developers/js/devsite_devsite_cse_module.js"});q.set("devsite-device",{src:"/developers/js/devsite_devsite_device_module.js"});q.set("devsite-devprofile",{src:"/developers/js/devsite_devsite_devprofile_module.js"});
q.set("devsite-dialog",{src:"/developers/js/devsite_devsite_dialog_module.js"});q.set("devsite-dropdown-list",{src:"/developers/js/devsite_devsite_dropdown_list_module.js"});q.set("devsite-dynamic-content",{src:"/developers/js/devsite_devsite_dynamic_content_module.js"});q.set("devsite-dynamic-hero",{src:"/developers/js/devsite_devsite_dynamic_hero_module.js"});q.set("devsite-edit-profile",{src:"/developers/js/devsite_devsite_edit_profile_module.js"});q.set("devsite-expandable",{src:"/developers/js/devsite_devsite_expandable_module.js"});
q.set("devsite-extradory",{src:"/developers/js/devsite_devsite_extradory_module.js"});q.set("devsite-fast-track-profile-creator",{src:"/developers/js/devsite_devsite_fast_track_profile_creator_module.js"});q.set("devsite-feature-tooltip",{src:"/developers/js/devsite_devsite_feature_tooltip_module.js"});q.set("devsite-feedback",{src:"/developers/js/devsite_devsite_feedback_module.js"});q.set("devsite-filter",{src:"/developers/js/devsite_devsite_filter_module.js"});
q.set("devsite-footer-linkboxes",{src:"/developers/js/devsite_devsite_footer_linkboxes_module.js"});q.set("devsite-footer-promos",{src:"/developers/js/devsite_devsite_footer_promos_module.js"});q.set("devsite-footer-utility",{src:"/developers/js/devsite_devsite_footer_utility_module.js"});q.set("devsite-fully-clickable",{src:"/developers/js/devsite_devsite_fully_clickable_module.js"});q.set("devsite-googler-buttons",{src:"/developers/js/devsite_devsite_googler_buttons_module.js"});
q.set("devsite-hats-survey",{src:"/developers/js/devsite_devsite_hats_survey_module.js"});q.set("devsite-header",{src:"/developers/js/devsite_devsite_header_module.js"});q.set("devsite-heading-link",{src:"/developers/js/devsite_devsite_heading_link_module.js"});q.set("devsite-iframe",{src:"/developers/js/devsite_devsite_iframe_module.js"});q.set("devsite-info-popout",{src:"/developers/js/devsite_devsite_info_popout_module.js"});q.set("devsite-jsfiddle-button",{src:"/developers/js/devsite_devsite_jsfiddle_button_module.js"});
q.set("devsite-json-validator",{src:"/developers/js/devsite_devsite_json_validator_module.js"});q.set("devsite-jump-to",{src:"/developers/js/devsite_devsite_jump_to_module.js"});q.set("devsite-language-selector",{src:"/developers/js/devsite_devsite_language_selector_module.js"});q.set("devsite-lightbox",{src:"/developers/js/devsite_devsite_lightbox_module.js"});q.set("devsite-mathjax",{src:"/developers/js/devsite_devsite_mathjax_module.js"});q.set("devsite-mdc",{src:"/developers/js/devsite_devsite_mdc_module.js"});
q.set("devsite-multiple-choice",{src:"/developers/js/devsite_devsite_multiple_choice_module.js"});q.set("devsite-mwc",{src:"/developers/js/devsite_devsite_mwc_module.js"});q.set("devsite-my-activity-light",{src:"/developers/js/devsite_devsite_my_activity_light_module.js"});q.set("devsite-my-community",{src:"/developers/js/devsite_devsite_my_community_module.js"});q.set("devsite-nav-buttons",{src:"/developers/js/devsite_devsite_nav_buttons_module.js"});q.set("devsite-notification",{src:"/developers/js/devsite_devsite_notification_module.js"});
q.set("devsite-pagination",{src:"/developers/js/devsite_devsite_pagination_module.js"});q.set("devsite-panel",{src:"/developers/js/devsite_devsite_panel_module.js"});q.set("devsite-playlist",{src:"/developers/js/devsite_devsite_playlist_module.js"});q.set("devsite-playlist-earnable-badges",{src:"/developers/js/devsite_devsite_playlist_earnable_badges_module.js"});q.set("devsite-playlist-summary",{src:"/developers/js/devsite_devsite_playlist_summary_module.js"});q.set("devsite-product-catalog",{src:"/developers/js/devsite_devsite_product_catalog_module.js"});
q.set("devsite-profile-card",{src:"/developers/js/devsite_devsite_profile_card_module.js"});q.set("devsite-progress",{src:"/developers/js/devsite_devsite_progress_module.js"});q.set("devsite-quiz",{src:"/developers/js/devsite_devsite_quiz_module.js"});q.set("devsite-recommendations",{src:"/developers/js/devsite_devsite_recommendations_module.js"});q.set("devsite-recommendations-dropdown",{src:"/developers/js/devsite_devsite_recommendations_dropdown_module.js"});
q.set("devsite-recommendations-sidebar",{src:"/developers/js/devsite_devsite_recommendations_sidebar_module.js"});q.set("devsite-recommended-content",{src:"/developers/js/devsite_devsite_recommended_content_module.js"});q.set("devsite-reference-results",{src:"/developers/js/devsite_devsite_reference_results_module.js"});q.set("devsite-related-entities",{src:"/developers/js/devsite_devsite_related_entities_module.js"});q.set("devsite-rich-tooltip",{src:"/developers/js/devsite_devsite_rich_tooltip_module.js"});
q.set("devsite-search",{src:"/developers/js/devsite_devsite_search_module.js"});q.set("devsite-search-summary",{src:"/developers/js/devsite_devsite_search_summary_module.js"});q.set("devsite-select",{src:"/developers/js/devsite_devsite_select_module.js"});q.set("devsite-selector",{src:"/developers/js/devsite_devsite_selector_module.js"});q.set("devsite-shell",{src:"/developers/js/devsite_devsite_shell_module.js"});q.set("devsite-shell-activate-button",{src:"/developers/js/devsite_devsite_shell_activate_button_module.js"});
q.set("devsite-sitemask",{src:"/developers/js/devsite_devsite_sitemask_module.js"});q.set("devsite-snackbar",{src:"/developers/js/devsite_devsite_snackbar_module.js"});q.set("devsite-sort",{src:"/developers/js/devsite_devsite_sort_module.js"});q.set("devsite-spinner",{src:"/developers/js/devsite_devsite_spinner_module.js"});q.set("devsite-support-form",{src:"/developers/js/devsite_devsite_support_form_module.js"});q.set("devsite-switch-to-english-button",{src:"/developers/js/devsite_devsite_switch_to_english_button_module.js"});
q.set("devsite-tabs",{src:"/developers/js/devsite_devsite_tabs_module.js"});q.set("devsite-thumb-rating",{src:"/developers/js/devsite_devsite_thumb_rating_module.js"});q.set("devsite-toc",{src:"/developers/js/devsite_devsite_toc_module.js"});q.set("devsite-tooltip",{src:"/developers/js/devsite_devsite_tooltip_module.js"});q.set("devsite-topic",{src:"/developers/js/devsite_devsite_topic_module.js"});q.set("devsite-tracking-question",{src:"/developers/js/devsite_devsite_tracking_question_module.js"});
q.set("devsite-user",{src:"/developers/js/devsite_devsite_user_module.js"});q.set("devsite-var",{src:"/developers/js/devsite_devsite_var_module.js"});q.set("devsite-version-selector",{src:"/developers/js/devsite_devsite_version_selector_module.js"});q.set("devsite-video",{src:"/developers/js/devsite_devsite_video_module.js"});q.set("devsite-view-release-notes",{src:"/developers/js/devsite_devsite_view_release_notes_module.js"});q.set("devsite-view-release-notes-dialog",{src:"/developers/js/devsite_devsite_view_release_notes_dialog_module.js"});
q.set("devsite-visibility-analytics",{src:"/developers/js/devsite_devsite_visibility_analytics_module.js"});q.set("devsite-vplus",{src:"/developers/js/devsite_devsite_vplus_module.js"});q.set("devsite-wall-acknowledgement",{src:"/developers/js/devsite_devsite_wall_acknowledgement_module.js"});q.set("devsite-youtube",{src:"/developers/js/devsite_devsite_youtube_module.js"});q.set("devsite-chip",{src:"/developers/js/devsite_devsite_chip_module.js"});q.set("google-codelab",{src:"/developers/js/devsite_google_codelab_module.js"});
q.set("google-codelab-about",{src:"/developers/js/devsite_google_codelab_about_module.js"});q.set("google-codelab-analytics",{src:"/developers/js/devsite_google_codelab_analytics_module.js"});q.set("google-codelab-step",{src:"/developers/js/devsite_google_codelab_step_module.js"});q.set("google-codelab-survey",{src:"/developers/js/devsite_google_codelab_survey_module.js"});q.set("devsite-avatar",{src:"/developers/js/devsite_devsite_avatar_module.js"});q.set("devsite-activity-list",{src:"/developers/js/devsite_devsite_activity_list_module.js"});
q.set("devsite-badge",{src:"/developers/js/devsite_devsite_badge_module.js"});q.set("devsite-card",{src:"/developers/js/devsite_devsite_card_module.js"});q.set("devsite-collection",{src:"/developers/js/devsite_devsite_collection_module.js"});q.set("devsite-collection-list",{src:"/developers/js/devsite_devsite_collection_list_module.js"});q.set("devsite-profile",{src:"/developers/js/devsite_devsite_profile_module.js"});q.set("devsite-profile-dashboard",{src:"/developers/js/devsite_devsite_profile_dashboard_module.js"});
q.set("devsite-profile-interests",{src:"/developers/js/devsite_devsite_profile_interests_module.js"});q.set("devsite-profile-recommendations",{src:"/developers/js/devsite_devsite_profile_recommendations_module.js"});q.set("devsite-profile-wizard",{src:"/developers/js/devsite_devsite_profile_wizard_module.js"});q.set("devsite-profile-router",{src:"/developers/js/devsite_devsite_profile_router_module.js"});q.set("devsite-profiles-splash",{src:"/developers/js/devsite_devsite_profiles_splash_module.js"});
q.set("devsite-youtube-playables-test-suite",{src:"/developers/js/devsite_devsite_youtube_playables_test_suite_module.js"});m("DevsiteAppAuthorizedElements",q);m("DevsiteAppTenantCustomized",!0);var ha={kc:0,jc:1,Mb:6,Kb:8,Sb:12,Tb:14,Ub:17,Yb:18,ac:21,cc:25,la:37,dc:38,ab:45,U:47,B:50,M:52,I:62,Ia:63,Eb:66,vb:70,C:73,kb:74,W:75,Bb:76,Ea:77,Ga:80,J:81,Ua:82,Aa:83,tb:85,da:87,va:89,xb:90,wa:91,Fa:92,S:93,hc:94,za:95,R:96,Fb:97,D:98,G:99,bc:100,sa:101,Ba:102,Ab:103,fc:104,ha:105,T:106,qa:107,ja:108,pb:109,ea:110,ec:112,Cb:113,ka:114,ma:116,Ya:117,Ta:118,xa:119,wb:120,Qb:121,Db:122,Wb:123,Lb:124,Pa:125,lb:126,ra:127,Rb:128,gb:129,hb:130,oa:131,Na:132,F:133,Ja:134,ta:135,Za:136,H:137,ic:138,
nb:139,Ob:140,Jb:141,fb:142,Ra:143,O:145,jb:146,Ka:147,Qa:148,yb:149,ca:151,La:152,Zb:156,Xb:157,Ha:158,na:159,K:160,X:161,ia:162,Pb:163,zb:164,aa:166,Gb:167,ba:168,Oa:169,Ma:170,ya:171,ib:174,qb:175,rb:176,mb:177,sb:178,Nb:179,Vb:180,Y:181,ga:182,P:183,ub:185,Ca:186,Va:187,Z:188,fa:189,Xa:190,L:191,N:192,Sa:193,Hb:194,ua:195,ob:196,pa:197,Ib:198,Wa:200,eb:203,Da:206,V:207,bb:208,cb:209};var r,t;a:{for(var ia=["CLOSURE_FLAGS"],v=d,w=0;w<ia.length;w++)if(v=v[ia[w]],null==v){t=null;break a}t=v}var ja=t&&t[610401301];r=null!=ja?ja:!1;var x;const ka=d.navigator;x=ka?ka.userAgentData||null:null;function y(a){return r?x?x.brands.some(({brand:b})=>b&&-1!=b.indexOf(a)):!1:!1}function z(a){var b;a:{if(b=d.navigator)if(b=b.userAgent)break a;b=""}return-1!=b.indexOf(a)};function A(){return r?!!x&&0<x.brands.length:!1}function B(){return A()?y("Chromium"):(z("Chrome")||z("CriOS"))&&!(A()?0:z("Edge"))||z("Silk")};var la=A()?!1:z("Trident")||z("MSIE");!z("Android")||B();B();z("Safari")&&(B()||(A()?0:z("Coast"))||(A()?0:z("Opera"))||(A()?0:z("Edge"))||(A()?y("Microsoft Edge"):z("Edg/"))||A()&&y("Opera"));var ma={},C=null;var na="undefined"!==typeof Uint8Array,oa=!la&&"function"===typeof btoa;var D;D="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol():void 0;var pa=D?(a,b)=>{a[D]|=b}:(a,b)=>{void 0!==a.g?a.g|=b:Object.defineProperties(a,{g:{value:b,configurable:!0,writable:!0,enumerable:!1}})},E=D?a=>a[D]|0:a=>a.g|0,F=D?a=>a[D]:a=>a.g,G=D?(a,b)=>{a[D]=b}:(a,b)=>{void 0!==a.g?a.g=b:Object.defineProperties(a,{g:{value:b,configurable:!0,writable:!0,enumerable:!1}})};function qa(a){a=a>>14&1023;return 0===a?536870912:a};var ra={},sa={};function ta(a){return!(!a||"object"!==typeof a||a.g!==sa)}function H(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}let I;function J(a,b,c){if(!Array.isArray(a)||a.length)return!1;const e=E(a);if(e&1)return!0;if(!(b&&(Array.isArray(b)?b.includes(c):b.has(c))))return!1;G(a,e|1);return!0}var ua;const va=[];G(va,55);ua=Object.freeze(va);class wa{}class xa{}Object.freeze(new wa);Object.freeze(new xa);function ya(a){if(null==a||"boolean"===typeof a)return a;if("number"===typeof a)return!!a}function za(a){return null==a?a:Number.isFinite(a)?a|0:void 0}function K(a){return null==a||"string"===typeof a?a:void 0};let L;function Aa(a,b){return Ba(b)}
function Ba(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "boolean":return a?1:0;case "object":if(a)if(Array.isArray(a)){if(J(a,void 0,0))return}else if(na&&null!=a&&a instanceof Uint8Array){if(oa){for(var b="",c=0,e=a.length-10240;c<e;)b+=String.fromCharCode.apply(null,a.subarray(c,c+=10240));b+=String.fromCharCode.apply(null,c?a.subarray(c):a);a=btoa(b)}else{void 0===b&&(b=0);if(!C){C={};c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split("");e=["+/=",
"+/","-_=","-_.","-_"];for(var h=0;5>h;h++){var f=c.concat(e[h].split(""));ma[h]=f;for(var g=0;g<f.length;g++){var k=f[g];void 0===C[k]&&(C[k]=g)}}}b=ma[b];c=Array(Math.floor(a.length/3));e=b[64]||"";for(h=f=0;f<a.length-2;f+=3){var l=a[f],p=a[f+1];k=a[f+2];g=b[l>>2];l=b[(l&3)<<4|p>>4];p=b[(p&15)<<2|k>>6];k=b[k&63];c[h++]=""+g+l+p+k}g=0;k=e;switch(a.length-f){case 2:g=a[f+1],k=b[(g&15)<<2]||e;case 1:a=a[f],c[h]=""+b[a>>2]+b[(a&3)<<4|g>>4]+k+e}a=c.join("")}return a}}return a};function Ca(a,b,c,e,h){if(null!=a){if(Array.isArray(a))a=J(a,void 0,0)?void 0:h&&E(a)&2?a:Da(a,b,c,void 0!==e,h);else if(H(a)){const f={};for(let g in a)f[g]=Ca(a[g],b,c,e,h);a=f}else a=b(a,e);return a}}function Da(a,b,c,e,h){const f=e||c?E(a):0;e=e?!!(f&32):void 0;a=Array.prototype.slice.call(a);for(let g=0;g<a.length;g++)a[g]=Ca(a[g],b,c,e,h);c&&c(f,a);return a}function Ea(a){return a.v===ra?a.toJSON():Ba(a)};var M=function(a,b){a=a.g;return Fa(a,F(a),b)},Fa=function(a,b,c){if(-1===c)return null;if(c>=qa(b)){if(b&256)return a[a.length-1][c]}else if(b=c+(+!!(b&512)-1),b<a.length)return a[b]};function N(a,b,c,e){const h=qa(b);if(c>=h){let f,g=b;if(b&256)f=a[a.length-1];else{if(null==e)return g;f=a[h+(+!!(b&512)-1)]={};g|=256}f[c]=e;c<h&&(a[c+(+!!(b&512)-1)]=void 0);g!==b&&G(a,g);return g}a[c+(+!!(b&512)-1)]=e;b&256&&(a=a[a.length-1],c in a&&delete a[c]);return b}
function O(a,b,c){a=a.g;let e=F(a);const h=2&e?1:2;var f=Fa(a,e,b);f=Array.isArray(f)?f:ua;let g=E(f);var k=4&g?!1:!0;if(k){if(4&g||Object.isFrozen(f))f=Array.prototype.slice.call(f),g=Ga(g,e),e=N(a,e,b,f);let l=k=0;for(;k<f.length;k++){const p=c(f[k]);null!=p&&(f[l++]=p)}l<k&&(f.length=l);c=g;0===c&&(c=Ga(c,e));g=c|21;g&=-12289;G(f,g);2&g&&Object.freeze(f)}2&g&&4&g||2048&g||(c=g,(k=1===h)?g|=2:g&=-33,g!==c&&G(f,g),k&&Object.freeze(f));2===h&&(2&g&&4&g||2048&g)&&(f=Array.prototype.slice.call(f),g=
Ga(g,e),G(f,g),N(a,e,b,f));return f}function Ha(a){a=a.g;let b=F(a);if(b&2)throw Error();N(a,b,2,"en")}function Ga(a,b){a=2&b?a|2:a&-3;a&=-33;return a&-2049}function P(a,b){return null!=a?a:b}var Q=function(a,b){return P(K(M(a,b)),"")};var Ia=function(){var a=R.config;I=!0;try{return JSON.stringify(a.toJSON(),Aa)}finally{I=!1}},Ka=class{constructor(a){a:{null==a&&(a=L);L=void 0;if(null==a){var b=96;a=[]}else{if(!Array.isArray(a))throw Error();b=E(a);if(b&64)break a;var c=a;b|=64;var e=c.length;if(e&&(--e,H(c[e]))){b|=256;c=e-(+!!(b&512)-1);if(1024<=c)throw Error();b=b&-16760833|(c&1023)<<14}}G(a,b)}this.g=a}toJSON(){return I?Ja(this,this.g,!1):Ja(this,Da(this.g,Ea,void 0,void 0,!1),!0)}};Ka.prototype.v=ra;
Ka.prototype.toString=function(){return Ja(this,this.g,!1).toString()};
function Ja(a,b,c){const e=a.constructor.A,h=F(c?a.g:b);a=b.length;if(!a)return b;let f,g;if(H(c=b[a-1])){a:{var k=c;let da={},ea=!1;for(var l in k){let u=k[l];if(Array.isArray(u)){let $a=u;if(J(u,e,+l)||ta(u)&&0===u.size)u=null;u!=$a&&(ea=!0)}null!=u?da[l]=u:ea=!0}if(ea){for(var p in da){k=da;break a}k=null}}k!=c&&(f=!0);a--}for(l=+!!(h&512)-1;0<a;a--){p=a-1;c=b[p];p-=l;if(!(null==c||J(c,e,p)||ta(c)&&0===c.size))break;g=!0}if(!f&&!g)return b;b=Array.prototype.slice.call(b,0,a);k&&b.push(k);return b}
;var La=class extends Ka{getTenantId(){var a=za(M(this,1));return P(a,0)}getLocale(){return Q(this,2)}getInsecureHost(){return Q(this,7)}},Ma=function(a){return b=>{if(null==b||""==b)b=new a;else{b=JSON.parse(b);if(!Array.isArray(b))throw Error(void 0);pa(b,32);L=b;b=new a(b);L=void 0}return b}}(La);La.A=[10,12,13,21,22];var S;var Na=class{constructor(a){this.g=a}toString(){return this.g+""}},Oa={};var Pa=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$"),Qa=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var e=a[c].indexOf("="),h=null;if(0<=e){var f=a[c].substring(0,e);h=a[c].substring(e+1)}else f=a[c];b(f,h?decodeURIComponent(h.replace(/\+/g," ")):"")}}};var T=function(a){this.j=this.s=this.i="";this.o=null;this.l=this.m="";this.g=!1;if(a instanceof T){this.g=a.g;Ra(this,a.i);this.s=a.s;this.j=a.j;Sa(this,a.o);this.m=a.m;var b=a.h;var c=new U;c.i=b.i;b.g&&(c.g=new Map(b.g),c.h=b.h);Ta(this,c);this.l=a.l}else a&&(b=String(a).match(Pa))?(this.g=!1,Ra(this,b[1]||"",!0),this.s=V(b[2]||""),this.j=V(b[3]||"",!0),Sa(this,b[4]),this.m=V(b[5]||"",!0),Ta(this,b[6]||"",!0),this.l=V(b[7]||"")):(this.g=!1,this.h=new U(null,this.g))};
T.prototype.toString=function(){var a=[],b=this.i;b&&a.push(W(b,Ua,!0),":");var c=this.j;if(c||"file"==b)a.push("//"),(b=this.s)&&a.push(W(b,Ua,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.o,null!=c&&a.push(":",String(c));if(c=this.m)this.j&&"/"!=c.charAt(0)&&a.push("/"),a.push(W(c,"/"==c.charAt(0)?Va:Wa,!0));(c=this.h.toString())&&a.push("?",c);(c=this.l)&&a.push("#",W(c,Xa));return a.join("")};
var Ra=function(a,b,c){a.i=c?V(b,!0):b;a.i&&(a.i=a.i.replace(/:$/,""))},Sa=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.o=b}else a.o=null},Ta=function(a,b,c){b instanceof U?(a.h=b,Ya(a.h,a.g)):(c||(b=W(b,Za)),a.h=new U(b,a.g))},ab=function(a){return a instanceof T?new T(a):new T(a)},V=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},W=function(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,bb),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,
"%$1")),a):null},bb=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Ua=/[#\/\?@]/g,Wa=/[#\?:]/g,Va=/[#\?]/g,Za=/[#\?@]/g,Xa=/#/g,U=function(a,b){this.h=this.g=null;this.i=a||null;this.j=!!b},X=function(a){a.g||(a.g=new Map,a.h=0,a.i&&Qa(a.i,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};U.prototype.add=function(a,b){X(this);this.i=null;a=Y(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h+=1;return this};
var cb=function(a,b){X(a);b=Y(a,b);a.g.has(b)&&(a.i=null,a.h-=a.g.get(b).length,a.g.delete(b))};U.prototype.clear=function(){this.g=this.i=null;this.h=0};var db=function(a,b){X(a);b=Y(a,b);return a.g.has(b)};U.prototype.forEach=function(a,b){X(this);this.g.forEach(function(c,e){c.forEach(function(h){a.call(b,h,e,this)},this)},this)};
var eb=function(a,b){X(a);let c=[];if("string"===typeof b)db(a,b)&&(c=c.concat(a.g.get(Y(a,b))));else for(a=Array.from(a.g.values()),b=0;b<a.length;b++)c=c.concat(a[b]);return c};U.prototype.set=function(a,b){X(this);this.i=null;a=Y(this,a);db(this,a)&&(this.h-=this.g.get(a).length);this.g.set(a,[b]);this.h+=1;return this};U.prototype.get=function(a,b){if(!a)return b;a=eb(this,a);return 0<a.length?String(a[0]):b};
U.prototype.toString=function(){if(this.i)return this.i;if(!this.g)return"";const a=[],b=Array.from(this.g.keys());for(var c=0;c<b.length;c++){var e=b[c];const f=encodeURIComponent(String(e)),g=eb(this,e);for(e=0;e<g.length;e++){var h=f;""!==g[e]&&(h+="="+encodeURIComponent(String(g[e])));a.push(h)}}return this.i=a.join("&")};
var Y=function(a,b){b=String(b);a.j&&(b=b.toLowerCase());return b},Ya=function(a,b){b&&!a.j&&(X(a),a.i=null,a.g.forEach(function(c,e){var h=e.toLowerCase();if(e!=h&&(cb(this,e),cb(this,h),0<c.length)){this.i=null;e=this.g;var f=e.set;h=Y(this,h);var g=c.length;if(0<g){const k=Array(g);for(let l=0;l<g;l++)k[l]=c[l];g=k}else g=[];f.call(e,h,g);this.h+=c.length}},a));a.j=b};/*

 SPDX-License-Identifier: Apache-2.0
*/
const fb={};function gb(a,b){var c=fb[a];if(void 0!==c&&(!c.u||Date.now()<=c.u+3E5))return c.p;c=new Promise((h,f)=>{b.onload=()=>h(b);b.onerror=g=>{b.parentNode&&b.parentNode.removeChild(b);f(g)};document.head.appendChild(b)});const e={u:0,p:c};c.catch(()=>e.u=+new Date);fb[a]=e;return c}
var hb=function(a){a=ab(a);const b=document.createElement("script");var c=a.toString();c=null===c?"null":void 0===c?"undefined":c;if(void 0===S){var e=null;var h=d.trustedTypes;if(h&&h.createPolicy){try{e=h.createPolicy("goog#html",{createHTML:n,createScript:n,createScriptURL:n})}catch(k){d.console&&d.console.error(k.message)}S=e}else S=e}c=(e=S)?e.createScriptURL(c):c;c=new Na(c,Oa);b.src=c instanceof Na&&c.constructor===Na?c.g:"type_error:TrustedResourceUrl";var f;let g;(f=(c=null==(g=(f=(b.ownerDocument&&
b.ownerDocument.defaultView||window).document).querySelector)?void 0:g.call(f,"script[nonce]"))?c.nonce||c.getAttribute("nonce")||"":"")&&b.setAttribute("nonce",f);return gb(a.toString(),b)};class ib{constructor(){this.promise=new Promise(a=>{this.g=a})}};var Z=function(a="Devsite has failed to load."){throw Error(a);},kb=async function(){var a=R;const b=new ib;m("__devsiteAppReadyResolver",b.g);m("__devsiteAppReadyPromise",b.promise);m("DevsiteApp.whenReady",()=>b.promise);if(O(a.config,12,K).length)try{await Promise.all(O(a.config,12,K).map(h=>{h=ab(h);const f=document.createElement("link");f.setAttribute("rel","stylesheet");f.setAttribute("type","text/css");f.setAttribute("href",h.toString());return gb(h.toString(),f)}))}catch(h){Z(`Failed to load Devsite App dependencies: ${h.message}`)}const c=
d.DevsiteAppTenantCustomized?Q(a.config,6):Q(a.config,5);try{await hb(`${c}${jb(a)}`)}catch(h){if("en"!==a.config.getLocale()){Ha(a.config);try{await hb(`${c}${Q(a.config,4)}`)}catch(f){Z(`Failed to load Devsite App binary: ${f.message}`)}}else Z(`Failed to load Devsite App binary: ${h.message}`)}const e=document;if("complete"!==e.readyState&&"interactive"!==e.readyState){const h=new ib;e.addEventListener("readystatechange",()=>{"interactive"!==e.readyState&&"complete"!==e.readyState||h.g()});await h.promise}},
jb=function(a){const b=a.config.getLocale();a=Q(a.config,4);return b&&"en"!==b?a.replace(/\.js$/,`__${b.toLowerCase().replace("-","_")}.js`):a};
const R=new class{constructor(){this.g=null;this.config=new La;this.h=[];this.i=a=>{this.h.push(a)};this.l=()=>{this.j()};if(d.__globalAppLoader)return d.__globalAppLoader;try{this.config=Ma(`${GoogleDevelopersObject}`.replaceAll("\n",""))}catch(a){Z("GoogleDevelopersObject missing or invalid")}GoogleDevelopersObject=null;m("__globalAppLoader",this);m("DevsiteApp.hasFlagAccess",a=>this.hasFlagAccess(a));m("DevsiteApp.hasMendelFlagAccess",(a,b)=>this.hasMendelFlagAccess(a,b))}j(){var a=document.querySelector("devsite-content");
a&&(window.removeEventListener("message",this.i),a.removeEventListener("devsite-content-updated",this.l));a=window;for(const b of this.h)a.dispatchEvent(b);this.h=[]}getEnv(){if(P(ya(M(this.config,11)),!1))return"PROD";const a=document.location.hostname;return a.endsWith("test.devsite.corp.google.com")||a.endsWith("test.devsite-v2-staging.googleplex.com")?"TEST":a.endsWith(".devsite.corp.google.com")||a.endsWith("devsite-v2-staging.googleplex.com")?"STAGE":"DEV"}hasFlagAccess(a){var b=this.getEnv();
var c=O(this.config,13,za);a:{var e=new URL(document.location.toString());e=new T(e.href);const h=Object.keys(ha);if("PROD"!==b)for(const f of h)if(ha[f]===a&&(b=e.h.get(f),void 0!==b)){a="true"===b;break a}a=Array.from(c).includes(a)}return a}hasMendelFlagAccess(a,b){var c=this.getEnv();var e=O(this.config,22,K);a:{var h=new URL(document.location.toString());h=new T(h.href);a=a+"__"+b;if("PROD"!==c&&(c=h.h.get(a),void 0!==c)){e="true"===c;break a}e=Array.from(e).includes(a)}return e}},lb=document.querySelector("devsite-content");
lb&&(window.addEventListener("message",R.i),lb.addEventListener("devsite-content-updated",R.j.bind(R)));(async function(){const a=window;if("WeakMap"in a&&"performance"in a&&"now"in a.performance)return R.g||(R.g=kb()),R.g})().then(()=>{P(ya(M(R.config,9)),!1)?(d.DevsiteAppFrameboxInit||Z("Failed to load Devsite App binary"),DevsiteAppFrameboxInit(Ia(),d.DevsiteAppAuthorizedElements)):(d.DevsiteAppInit||Z("Failed to load Devsite App binary"),DevsiteAppInit(Ia(),d.DevsiteAppAuthorizedElements))});}).call(this);
