(function(_ds){var window=this;var G0=function(a){return!a.classList.contains("material-icons")},Qaa=async function(a,b){var c=await _ds.v();const d=_ds.F();c=c.getInsecureHost();b=b.Ga;var e=b.origin===d.origin;if(c){if(b.origin!==c&&!e)return}else if(!e)return;let f;try{f=(0,_ds.Pn)(b.data)}catch(g){return}c=_ds.kh(f,1);if(4===c)await Iaa(a,b);else if(e=f.getName())if(e=a.querySelector(`devsite-iframe iframe[name="${e}"]`))switch(c){case 5:await Jaa(b,f,e);break;case 8:await Kaa(b,f,d);break;case 1:await Laa(b,f,d);break;case 6:case 7:await Maa(c,
d,f);break;case 9:await Naa(a,f);break;case 10:await Oaa(f,d);break;case 13:await Paa(f)}},H0=function(a){Array.from(a.querySelectorAll("table.lazy-load")).forEach(b=>{b.classList.remove("hidden")})},Raa=async function(a,b){if(b.detail){var c=b.detail.bottomPanelHeight,d=b.detail.contentHeight,e=b.detail.contentMargin,f=b.detail.offset,g=b.detail.panelCoversContent,h=b.detail.x;b=b.detail.y;var k=new _ds.Kn;c=_ds.qh(k,8,c);d=_ds.qh(c,6,d);e=_ds.qh(d,7,e);f=_ds.qh(e,5,f);g=_ds.ph(f,9,g);h=_ds.qh(g,
1,h);h=_ds.qh(h,2,b);h=_ds.qh(_ds.qh(h,3,_ds.ik().height),4,_ds.ik().width);b=_ds.Mn(13);h=_ds.Xg(b,13,h);for(const l of a.iframes)l&&l.contentWindow&&I0(l.contentWindow,h)}},J0=function(a){Saa(a);a.o=a.querySelector(".devsite-article-body");a.o&&(Taa(a),a.iframes=[]);a.g&&a.g.disconnect();a.h.clear();Uaa(a);if(!document.body.hasAttribute("appearance")){var b=[...a.querySelectorAll("picture > source.devsite-dark-theme")];for(var c of b){b=c.closest("picture");var d=void 0;const e=null==(d=b)?void 0:
d.querySelectorAll("source:not(.devsite-dark-theme)");let f;const g=null==(f=b)?void 0:f.querySelector("img");let h;(null==(h=e)?0:h.length)?c.remove():b&&g&&b.replaceWith(g)}}c=Array.from(a.querySelectorAll(".devsite-nav-title, .devsite-page-title, td > code, th > code"));"docs"===document.body.getAttribute("layout")&&a.o&&(d=Array.from(a.o.querySelectorAll("h1, h2, h3, h4, h5, h6")),c.push(...d));a.h.clear();a.h=new Set(c);if(_ds.F().hash){c=new _ds.dL;for(const e of a.h)_ds.cL(c,e,G0)}else Vaa(a,
a.h);a.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0}))},Uaa=function(a){Array.from(a.querySelectorAll("*:not(.devsite-table-wrapper) > table")).forEach(b=>{const c=document.createElement("div");c.classList.add("devsite-table-wrapper");b.classList.contains("full-width")&&(c.classList.add("devsite-full-width-table"),b.classList.remove("full-width"));_ds.rk(c,b);c.appendChild(b)})},Saa=function(a){Array.from(a.querySelectorAll("table.lazy-load")).forEach(b=>{b.classList.add("hidden")})},
Iaa=async function(a,b){if(b.source){var c=Waa(a,b.source);if(c){const e="goog_"+_ds.Xj++;c.setAttribute("name",e);var d=_ds.Mn(3);d=_ds.sh(d,2,e);I0(b.source,d);(b=document.body.getAttribute("appearance"))&&K0(c,b);a.iframes.push(c)}}},Jaa=async function(a,b,c){await _ds.jf();var d=_ds.kk(document).y,e=_ds.hh(b,4);const f=_ds.hh(b,3);a:{var g;if(_ds.yj&&(g=c.parentElement)){c=g;break a}g=c.parentNode;c=_ds.uf(g)&&1==g.nodeType?g:null}e&&(null==c||c.setAttribute("width",`${e}px`));f&&(null==c||c.setAttribute("height",
`${f}px`));window.scrollTo({left:_ds.kk(document).x,top:d});_ds.kf();d=new _ds.Kn;d=_ds.qh(d,1,window.scrollX);d=_ds.qh(_ds.qh(_ds.qh(d,2,window.scrollY),3,_ds.ik().height),4,_ds.ik().width);e=_ds.Mn(5);d=_ds.Xg(e,13,d);b=_ds.Nn(d,_ds.z(b,8));I0(a.source,b)},Kaa=async function(a,b,c){a.source&&(b=_ds.Nn(_ds.Mn(8),_ds.z(b,8)),c=_ds.sh(b,6,c.toString()),I0(a.source,c))},Laa=async function(a,b,c){a.source&&(b=_ds.Nn(_ds.Mn(2),_ds.z(b,8)),c=_ds.sh(b,7,`${c.search}${c.hash}`),I0(a.source,c))},Maa=async function(a,
b,c){const d=c.getTitle();c=new URL(c.getUrl(),b.origin);b.search=c.search;b.hash=c.hash;b=b.href.replace(b.origin,"");6===a?_ds.sl(b,!1,!0,void 0,void 0,d):_ds.sl(b,!0,!0,void 0,void 0,d)},Naa=async function(a,b){const c=_ds.z(b,9);let d;try{d=JSON.parse(_ds.z(b,10))}catch(e){console.warn("Event data from Framebox is not valid JSON.",a);return}"analyticsEvent"===c?a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:d,bubbles:!0})):"cloudtrackEvent"===c?a.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",
{detail:{eventData:d},bubbles:!0})):"devsite-apix"===c&&a.dispatchEvent(new CustomEvent("devsite-apix-observation",{detail:d,bubbles:!0}))},Oaa=async function(a,b){a=a.getUrl();const c=await _ds.v();if(a){const d=new URL(a,b.origin);a.startsWith("#")||b.origin===d.origin&&b.pathname===d.pathname&&b.search===d.search?await c.scrollToAnchor(d.hash,!0):await c.fetchPage(d.href)}},Paa=async function(a){var b;const c=(null==(b=_ds.On(a))?void 0:_ds.hh(b,1))||0;let d;b=(null==(d=_ds.On(a))?void 0:_ds.hh(d,
2))||0;let e;window.scrollTo({left:c,top:b,behavior:(null==(e=_ds.On(a))?0:_ds.gh(e,10))?"smooth":"auto"})},I0=function(a,b){a&&a.postMessage(_ds.vh(b),"*")},Waa=function(a,b){let c;Array.from(a.querySelectorAll("devsite-iframe iframe")).forEach(d=>{_ds.zk(d)===b&&(c=d)});return c},K0=function(a,b){var c=_ds.Mn(12);b=_ds.sh(c,12,b);a&&a.contentWindow&&I0(a.contentWindow,b)},Taa=function(a){if("full"===document.body.getAttribute("layout")){let b;(a=null==(b=a.o)?void 0:b.querySelectorAll('h1[tabindex="0"],h2[tabindex="0"],h3[tabindex="0"],h4[tabindex="0"],h5[tabindex="0"],h6[tabindex="0"]'))&&
Array.from(a).forEach(c=>{c.removeAttribute("tabindex")})}},Vaa=function(a,b){a.g&&b.forEach(c=>{let d;null==(d=a.g)||d.observe(c)})},L0=class extends _ds.E{constructor(){super();this.eventHandler=new _ds.G;this.v=new _ds.G;this.h=new Set;this.o=null;this.iframes=[];this.g=null;"IntersectionObserver"in window&&(this.g=new IntersectionObserver(a=>{for(const b of a)if(b.isIntersecting){a=b.target;_ds.cL(new _ds.dL,a,G0);this.h.delete(a);let c;null==(c=this.g)||c.unobserve(a)}},{rootMargin:"100%"}))}connectedCallback(){this.eventHandler.listen(window,
"message",a=>{Qaa(this,a)});this.eventHandler.listen(document.body,"devsite-appearance-updated",a=>{if(a=a.Ga.detail.preference)for(const b of this.iframes)K0(b,a)});this.eventHandler.listen(document.body,"devsite-page-loaded",()=>{H0(this)});this.eventHandler.listen(document.body,"devsite-sticky-scroll",a=>{Raa(this,a.Ga)});J0(this)}disconnectedCallback(){this.g&&this.g.disconnect();this.h.clear();_ds.I(this.eventHandler);_ds.I(this.v)}Rb(a){a&&([".devsite-article",".devsite-content-data","devsite-content-footer",
"devsite-notification"].forEach(b=>{_ds.tj(this,this.querySelector(b),a.querySelector(b))}),J0(this),H0(this))}};L0.prototype.updateContent=L0.prototype.Rb;L0.prototype.disconnectedCallback=L0.prototype.disconnectedCallback;L0.prototype.connectedCallback=L0.prototype.connectedCallback;try{customElements.define("devsite-content",L0)}catch(a){console.warn("devsite.app.customElement.DevsiteContent",a)};})(_ds_www);
