(function(_ds){var window=this;var Xaa=async function(){if("loading"===document.readyState)return new Promise(a=>{document.addEventListener("DOMContentLoaded",()=>{a()})})},O0=function(a){return!!a&&(a.classList.contains("glue-footer__global-links-list-item")||a.classList.contains("h-c-footer__global-links-list-item"))},P0=function({category:a,siteId:b},c){return d=>d.category===a&&d.siteId===b&&d.eea===c},Q0=function(...a){return arguments},S0=function(a,b,c){return Q0("consent",a,{ad_storage:R0(c),analytics_storage:R0(b)})},
R0=function(a=!1){return a?"granted":"denied"},T0=function(a,b=!1,c=!1,d=!1){return{event:"user_consent",cookieConsent:"UNKNOWN"===a?"none":`${"ACCEPTED"===a}`,isEEA:`${b}`,adsStorage:`${d}`,analyticsStorage:`${c}`}},U0="ar bg ca cs da de el en en-GB es es-419 et eu fi fr fr-CA gl hr hu is it iw ja ko lt lv mt nl no pl pt-BR pt-PT ro ru sk sl sr sv tr uk".split(" ");var Yaa={XE:"2A",ZE:"2B"},Zaa={Wy:"ACCEPTED",kE:"REJECTED",UNKNOWN:"UNKNOWN"};var $aa=class{constructor(a){this.j=a;this.delay=250}debounce(){clearTimeout(this.g);this.g=window.setTimeout(this.j,this.delay)}cancel(){clearTimeout(this.g)}};window.dataLayer=window.dataLayer||[];
var V0=0,W0=function(a,b,c){a.events.dispatchEvent(new CustomEvent(b,{detail:c}))},X0=function(){try{const a=window.localStorage.getItem("glue.CookieNotificationBar"),b=a&&JSON.parse(a);return Array.isArray(b)?b.map(c=>{if(!(c instanceof Object)||Array.isArray(c))return null;const d=c.category;var e=c.date;const f=c.eea,g=c.siteId;c=c.status;return(e=e&&new Date(e))&&!isNaN(Number(e))&&Object.values(Yaa).includes(d)&&"string"===typeof g&&Object.values(Zaa).includes(c)?{category:d,date:e,eea:f,siteId:g,
status:c}:null}).filter(c=>!!c):[]}catch(a){return console.error(a),[]}},Y0=async function(a){const b=await a.rendered;b instanceof HTMLElement&&a.j&&(a.visible?a.j.style.marginBottom=`${getComputedStyle(b).height}`:"0px"!==a.j.style.marginBottom&&(a.j.style.marginBottom="0px"))},aba=function(a,b){a.controls.push(...document.querySelectorAll(".glue-cookie-notification-bar-control"));for(const c of a.controls)c.addEventListener("click",a.ma),c.removeAttribute("aria-hidden"),c.setAttribute("aria-controls",
a.id),c.setAttribute("aria-expanded","false"),c.textContent=b,c instanceof HTMLButtonElement||c.addEventListener("keydown",a.qa),O0(c.parentElement)&&c.parentElement.removeAttribute("aria-hidden")},Z0=class{constructor(a=document.body,b){this.root=a;this.controls=[];this.events=document.createElement("div");this.ea=!1;this.h="UNKNOWN";this.ua=!1;this.Aa=c=>{this.g=c.eea;{var d=P0(this.options,this.g);const e=X0().find(d);e?(d=new Date,d.setMonth(d.getMonth()-13),d=e.date>d?e.status:"UNKNOWN"):d="UNKNOWN"}this.h=
c.required||"UNKNOWN"!==d?d:"ACCEPTED";"2A"===this.options.category&&window.dataLayer.unshift(Q0("set","url_passthrough",!0),S0("default",!1,!1),S0("update",this.v,this.o),T0(this.g||!c.required?"UNKNOWN":this.status,this.g,this.v,this.o));d={required:c.required,status:this.status};this.g&&(d.eea=this.g);W0(this,"loaded",d);if(c.required)return this.listen("statuschange",this.Fa),"UNKNOWN"===this.status&&this.open(),this.render(c)};this.xa=c=>{c.preventDefault();this.status="ACCEPTED";this.close()};
this.ma=c=>{c.preventDefault();this.open(!0)};this.qa=c=>{switch(c.key){case "Enter":case " ":c.preventDefault(),this.open(!0)}};this.Ca=c=>{c.preventDefault();this.status="REJECTED";this.close()};this.Fa=({detail:{status:c}})=>{if("2A"===this.options.category&&!this.g){var d="ACCEPTED"===this.status;window.dataLayer.push(S0("update",this.options.analyticsStorage||d,d),T0(this.status,this.g,this.v,this.o))}const e=P0(this.options,this.g);d=X0().filter(f=>!e(f));d.push({category:this.options.category,
date:new Date,eea:this.g,siteId:this.options.siteId,status:c});try{window.localStorage.setItem("glue.CookieNotificationBar",JSON.stringify(d))}catch(f){console.error(f)}};this.va=()=>{Y0(this)};this.oa=()=>{this.Ha.debounce()};this.options=Object.assign({},Z0.g,b);V0+=1;this.id=`glue-cookie-notification-bar-${V0}`;window.glueCookieNotificationBarLoaded&&this.listen("loaded",window.glueCookieNotificationBarLoaded);this.j=document.querySelector(`.${this.options.autoMarginClass}`);this.Ha=new $aa(this.va);
this.config=this.fetch();this.rendered=this.config.then(this.Aa)}async fetch(){const [a,b]=this.options.language.split(/[-_]/);var c=`${a}-${(b||a).toUpperCase()}`;c=U0.includes(c)?c:U0.includes(a)?a:"";const d="2A"===this.options.category?"/glue/cookienotificationbar/config/2a.json":"/glue/cookienotificationbar/config/2b.json";try{return await (await fetch(`${"https://www.gstatic.com"}${d}${c?`?hl=${c}`:""}`)).json()}catch(e){return console.error(e),{required:!1}}}async render(a){await Xaa();this.root||
(this.root=document.body);const b=Object.assign({},a.content,this.options.content),c=`${this.id}-label`;var d=b.mainText.replace(/\[(.+)\]/,()=>this.options.siteId);const e=document.createElement("div");e.classList.add("glue-cookie-notification-bar");e.id=this.id;e.setAttribute("aria-hidden","true");e.setAttribute("aria-labelledby",c);e.setAttribute("inert","true");e.setAttribute("role","region");e.tabIndex=-1;this.options.language!==a.language&&(e.dir=a.rtl?"rtl":"ltr",e.lang=a.language);const f=
document.createElement("p");f.classList.add("glue-cookie-notification-bar__text");e.appendChild(f);const g=document.createElement("span");g.id=c;g.textContent=`${d} `;f.appendChild(g);d=document.createElement("a");_ds.Be(d,b.moreUrl);d.classList.add("glue-cookie-notification-bar__more");d.rel="noopener";d.setAttribute("aria-describedby",c);d.target="_blank";d.textContent=b.moreText;d.ariaLabel=b.moreAriaLabelText;f.appendChild(d);f.appendChild(document.createTextNode("ja"===a.language?"\u3002":"."));
a=document.createElement("button");a.addEventListener("click",this.xa);a.classList.add("glue-cookie-notification-bar__accept");a.textContent=b.consentText;e.appendChild(a);b.rejectText&&(a=document.createElement("button"),a.addEventListener("click",this.Ca),a.classList.add("glue-cookie-notification-bar__reject"),a.textContent=b.rejectText,e.appendChild(a));b.managementText&&aba(this,b.managementText);this.j&&window.addEventListener("resize",this.oa);this.root.prepend(e);return e}get visible(){return this.ua}open(a=
!1){return this.toggle(!0,a)}close(){return this.toggle(!1)}async toggle(a,b=!1){const c=await this.rendered;if(c&&a!==this.visible){if(!this.ea){this.ea=!0;var d=document.querySelector("html");if(d){({fontSize:d}=window.getComputedStyle(d));var e=Number(d.replace("px",""));window.getComputedStyle(c).fontSize===d&&18>=e&&(c.style.fontSize=`${16/e}rem`)}}a?(c.removeAttribute("aria-hidden"),c.removeAttribute("inert"),b&&c.focus()):(c.setAttribute("aria-hidden","true"),c.setAttribute("inert","true"),
c.blur());b=`${a}`;for(const f of this.controls)f.setAttribute("aria-expanded",b);this.ua=a;W0(this,"visibilitychange",{visible:a});await Y0(this)}else c&&a&&b&&c.focus()}listen(a,b){this.events.addEventListener(a,b)}unlisten(a,b){this.events.removeEventListener(a,b)}get status(){return this.h}set status(a){a!==this.h&&(this.h=a,W0(this,"statuschange",{status:a}))}get ra(){return"ACCEPTED"===this.status}get v(){return this.g||this.options.analyticsStorage||this.ra}get o(){return!this.g&&this.ra}async destroy(){const a=
await this.rendered;(null==a?0:a.parentNode)&&a.parentNode.removeChild(a);for(const b of this.controls)b.removeEventListener("click",this.ma),b.setAttribute("aria-hidden","true"),b instanceof HTMLButtonElement||b.removeEventListener("keydown",this.qa),O0(b.parentElement)&&b.parentElement.setAttribute("aria-hidden","true");this.j&&(this.j.style.marginBottom="0px",window.removeEventListener("resize",this.oa))}static get g(){return{analyticsStorage:!1,category:"2A",language:document.documentElement.lang,
siteId:location.host,autoMarginClass:"glue-footer"}}};var $0=function(){return"devsite-cookie-notification-bar"},bba=function(a){a.g&&(a.g.listen("loaded",async()=>{a.h.g();const b=await _ds.v();await b.hasMendelFlagAccess("Analytics","open_cookie_bar")&&a.g&&await a.g.open();await a1(a);await a.hasAccepted()?await b.getStorage().set("cookies_accepted","","true"):(await b.getStorage().remove("cookies_accepted",""),await _ds.Ko(b.getStorage()))}),a.g.listen("visibilitychange",()=>{a1(a)}),a.g.listen("statuschange",async()=>{const b=await _ds.v();await a.hasAccepted()?
"true"!==await b.getStorage().get("cookies_accepted","")&&await b.getStorage().set("cookies_accepted","","true"):(await b.getStorage().remove("cookies_accepted",""),await _ds.Ko(b.getStorage()))}))},a1=async function(a){if(a.g){var b=await a.g.rendered;b instanceof HTMLElement&&(await a.isVisible()?document.body.style.setProperty("--devsite-cookie-bar-height",getComputedStyle(b).height):document.body.style.removeProperty("--devsite-cookie-bar-height"))}},b1=class extends _ds.AA{constructor(){super(...arguments);
this.h=new _ds.hf;this.g=null;this.o=!1}Va(){return this}async connectedCallback(){super.connectedCallback();await this.setup();bba(this)}disconnectedCallback(){super.disconnectedCallback();if(this.g){let a;null==(a=this.g)||a.destroy()}document.body.style.removeProperty("--devsite-cookie-bar-height");this.h=new _ds.hf}async setup(){const a=await _ds.v(),b=document.documentElement.lang||"en";var c=a.getConfig();const d=_ds.z(c,16),e=_ds.kh(c,30);c=_ds.gh(c,31);4===e?this.g=new Z0(this,{category:"2A",
language:b,siteId:d,analyticsStorage:c}):3===e?this.g=new Z0(this,{category:"2B",language:b,siteId:d,analyticsStorage:c}):await a.hasMendelFlagAccess("Analytics","open_cookie_bar")?this.g=new Z0(this,{category:"2A",language:b,siteId:d,analyticsStorage:c}):(this.o=!0,this.h.g())}async hasAccepted(){await this.ready();if(this.o)return!0;let a;return"ACCEPTED"===(null==(a=this.g)?void 0:a.status)||!1}async isVisible(){await this.ready();let a;return(null==(a=this.g)?void 0:a.visible)||!1}ready(){return this.h.promise}async getCookieNotificationBar(){await this.ready();
return this.g}};b1.prototype.getCookieNotificationBar=b1.prototype.getCookieNotificationBar;b1.getTagName=$0;try{window.customElements.define($0(),b1)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteCookieNotificationBar",a)};})(_ds_www);
