(function(_ds){var window=this;var E2=function(a,b){b="translate3d("+b+"px,0px,0px)";_ds.Xm(a,D2(),b)},D2=_ds.Cj(function(){return _ds.cg&&9==_ds.xg?"-ms-transform":"transform"});var H2=function(a){a.h=F2(a,".devsite-top-logo-row-wrapper-wrapper");a.g=F2(a,".devsite-collapsible-section");a.o=F2(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",`${a.h}`);a.setAttribute("bottom-row--height",`${a.g}`);a.setAttribute("bottom-tabs--height",`${a.o}`);a.style.setProperty("--devsite-js-top-row--height",`${a.h}px`);a.style.setProperty("--devsite-js-bottom-row--height",`${a.g}px`);a.style.setProperty("--devsite-js-bottom-tabs--height",`${a.o}px`);G2(a)},G2=function(a){const b=
a.querySelector(".devsite-collapsible-section");a.offset>=a.g&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.offset<a.g-a.o&&a.hasAttribute("bottom-row--hidden")&&a.removeAttribute("bottom-row--hidden");b&&a.offset!==a.ua&&(_ds.Xm(b,"transform",`translate3d(0, -${a.offset}px, 0)`),I2(a),a.ua=a.offset);document.body.style.setProperty("--devsite-js-header-height",`${a.v()}px`)},vca=function(a){var b=a.querySelector(".devsite-top-logo-row-middle");const c=a.querySelector("devsite-search"),
d=a.querySelector(".devsite-search-background");if(b&&c&&d){_ds.I(a.qa);a.ea&&window.cancelAnimationFrame(a.ea);c.removeAttribute("transition");a.removeAttribute("search-expanded");var e=new _ds.Nj(b.offsetWidth,b.offsetHeight);b=new _ds.Nj(c.offsetWidth,c.offsetHeight);var f=_ds.qn(c),g="rtl"===document.documentElement.getAttribute("dir")?1:-1,h=(e.width-f.left-f.right)/b.width;e=(e.width-(b.width+f.left+f.right))*g;var k=(f=a.hasAttribute("search-active"))?e:0,l=f?h:1;_ds.Xm(d,{opacity:1,width:`${b.width}px`,
height:`${b.height}px`});E2(c,a.hasAttribute("search-active")?0:e);_ds.Tm(a.qa,d,_ds.Gh,()=>{const m=a.querySelector("devsite-search"),n=a.querySelector(".devsite-search-background");n&&(n.style.opacity="0");m&&(m.removeAttribute("transition"),E2(m,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.ea=window.requestAnimationFrame(()=>{c.setAttribute("transition","");var m="scale3d("+l+",1,1)";_ds.Xm(d,D2(),m);E2(c,k)})}},wca=async function(a,
b){if(a.hasAttribute("billboard")){var c=a.querySelector("devsite-search"),d=a.querySelector("devsite-search input.devsite-search-query");a=a.querySelector(".devsite-header-billboard-search devsite-search");var e=null==a?void 0:a.querySelector("input.devsite-search-query");c&&d&&a&&e&&(b?(c.removeAttribute("disabled"),document.activeElement===e&&(await _ds.Gl(),d.focus()),a.setAttribute("disabled","")):(a.removeAttribute("disabled"),document.activeElement===d&&e.focus(),c.setAttribute("disabled",
"")))}},xca=function(a){a.eventHandler.listen(a,"devsite-search-toggle",b=>{b=b.Ga;_ds.Jk(b.target,null,"devsite-top-logo-row-middle")&&(b.detail.active?a.setAttribute("search-active",""):a.removeAttribute("search-active"))});a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>document.body.removeAttribute("devsite-book-nav--open"));a.eventHandler.listen(window,"resize",()=>J2(a));a.eventHandler.listen(document.body,["devsite-page-loaded","devsite-content-updated"],()=>{J2(a)});a.eventHandler.listen(a,
"click",b=>{b.defaultPrevented||"devsite-hamburger-menu"!==b.target.getAttribute("id")||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",{bubbles:!0})))})},K2=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){const b=document.createElement("div");b.classList.add("devsite-search-background");b.style.opacity="1";a.appendChild(b)}},I2=
function(a){0===a.g?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},J2=function(a){window.requestAnimationFrame(()=>a.ra.Qa())},F2=function(a,b){return(a=a.querySelector(b))?a.getBoundingClientRect().height:0},L2=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=0;c<a.attributes.length;++c)d=
a.attributes.item(c),b.setAttribute(d.name,d.value)},M2=function(a,b,c){b=b.querySelector(c);c=a.querySelector(c);b&&c&&(a.updated=!0,_ds.tj(a,c,b))},yca=class extends _ds.E{constructor(){super(...arguments);this.eventHandler=new _ds.G;this.ua=-1;this.qa=new _ds.G;this.ea=0;this.ma=new MutationObserver(()=>H2(this));this.ra=new _ds.Qm(()=>{H2(this);I2(this)},15);this.authUser=void 0;this.offset=this.o=this.g=this.h=0;this.updated=!1}static get observedAttributes(){return["offset","search-active",
"bottom-row--hidden"]}attributeChangedCallback(a,b,c){switch(a){case "offset":this.offset=Number(this.getAttribute("offset")||"")||0;G2(this);break;case "search-active":vca(this);break;case "bottom-row--hidden":a=null!==c,b=this.querySelector("devsite-search input.devsite-search-query"),c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),wca(this,a)}}connectedCallback(){xca(this);K2(this);I2(this);H2(this);this.ma.observe(this,
{childList:!0,subtree:!0});G2(this);const a=_ds.F();this.authUser=_ds.fl(_ds.gl(a.href),"authuser")}disconnectedCallback(){_ds.I(this.eventHandler);this.ma.disconnect()}v(){return this.h+this.g-this.offset}oa(){return this.h+this.g}Rb(a){this.updated=!1;if(a){M2(this,a,".devsite-header-upper-tabs");M2(this,a,".devsite-collapsible-section");M2(this,a,".devsite-product-name-wrapper");M2(this,a,"devsite-language-selector");M2(this,a,"devsite-shell-activate-button");var b=a.querySelector("devsite-search"),
c=this.querySelector("devsite-search");b&&c&&L2(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&(L2(c,b),c=_ds.F(),c=_ds.fl(_ds.gl(c.href),"authuser"),c!==this.authUser&&(this.authUser=c,b.refresh()));_ds.tj(this,this.querySelector("cloudx-additional-tabs"),a.querySelector("cloudx-additional-tabs"),this.querySelector(".devsite-top-logo-row-middle"));_ds.tj(this,this.querySelector(".devsite-header-link"),a.querySelector(".devsite-header-link"),this.querySelector("devsite-language-selector"))}!this.updated&&
a&&(_ds.qk(this),this.appendChild(a));K2(this);J2(this)}};try{customElements.define("devsite-header",yca)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
