(function(_ds){var window=this;var BZ=function(){return(0,_ds.U)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},CZ=function(){return(0,_ds.U)('<div class="devsite-book-nav-blur"></div>')},DZ=function(a){a=a.Rw;a=_ds.mC(new _ds.iC("{NUMBER_OF_MATCHING_DESCENDANTS,plural,=1{{XXX_1} match}other{{XXX_2} matches}}"),{NUMBER_OF_MATCHING_DESCENDANTS:a,XXX_1:_ds.X(_ds.Xr(1)),XXX_2:_ds.X(_ds.Xr(a))});return(0,_ds.U)('<span class="devsite-nav-filter-match-count"> (<mark>'+
a+"</mark>)</span>")};var EZ="onpointerover"in window?"pointerover":"mouseover",FZ=function(a){const b=0<a.querySelectorAll(".devsite-nav-item").length,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.D(a,"visually-hidden","",c))},NZ=function(a){a.eventHandler.listen(a,"click",b=>void GZ(a,b));a.eventHandler.listen(a,"keypress",b=>{13===b.keyCode&&GZ(a,b)});a.eventHandler.listen(a,[EZ,"focusin"],b=>void HZ(a,b));a.eventHandler.listen(document.body,"devsite-sitemask-hidden",
()=>{a.h&&(IZ(a,"_book")?a.removeAttribute("top-level-nav"):_ds.D(a,"top-level-nav",""))});a.eventHandler.listen(document.body,"devsite-page-loaded",()=>void a.ua.Qa());a.eventHandler.listen(a,"devsite-content-updated",()=>{a.ua.Qa()});a.eventHandler.listen(a,"scroll",()=>{_ds.D(a,"user-scrolled","")});a.eventHandler.listen(a.Qb,"click",()=>{JZ(a)});a.g&&(a.eventHandler.listen(a.g,"keyup",()=>void a.va.Qa()),a.eventHandler.listen(a.g,"focus",()=>void KZ(a,"focus")));a.ma&&a.eventHandler.listen(a.ma,
["click","keydown"],b=>{if("click"===b.type||13===b.keyCode||27===b.keyCode){a.g&&(a.g.value="",a.g.focus());let c;null==(c=a.ma)||c.classList.add("hidden");LZ(a);MZ(a);KZ(a,b.type)}})},PZ=function(a,b=a,c=!0){b=Array.from(b.querySelectorAll(".devsite-nav-title"));a.ea=new Set(b);if(!_ds.F().hash&&c)OZ(a,a.ea);else{c=new _ds.dL;for(const d of a.ea)_ds.cL(c,d)}},QZ=async function(a){const b=await _ds.v();for(const c of a.ea)b.unregisterIntersectionForElement(c)},GZ=function(a,b){if(!b.defaultPrevented){var c=
b.target;"devsite-close-nav"===c.getAttribute("id")&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})):_ds.D(a,"top-level-nav",""));if(c.hasAttribute("menu")){var d=c.getAttribute("menu");d&&IZ(a,d)&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.removeAttribute("top-level-nav"))}var e=c.closest(".devsite-expandable-nav");if(e&&(d=c.closest(".devsite-nav-title, .devsite-nav-toggle"))){let f=
b.target,g,h;if(!(null==(g=f)?0:null==(h=g.closest(".devsite-nav-title"))?0:h.hasAttribute("href"))){for(b="click"===b.type||"touchend"===b.type;f&&f!==e;){if(f.classList.contains("devsite-nav-title-no-path")&&b){f.blur();break}f=f.parentNode}e.querySelector(".devsite-nav-section")&&(b=e.classList.toggle("expanded"),(e=e.querySelector(".devsite-nav-title"))&&_ds.D(a,"aria-expanded",`${b}`,e))}if(d.matches(".devsite-nav-toggle"))return}c.closest(".devsite-nav-title-no-path")||(a.h&&(d=a.h.querySelector("[menu=_book]"))&&
d.contains(c)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})),(c=c.closest("a.devsite-nav-title"))&&!c.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})))}},HZ=function(a,b){b.defaultPrevented||(b=_ds.Ik(b.target,c=>c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a,!0),b!==a&&_ds.Be(b,_ds.xe(_ds.zl(b.href).href)))},JZ=async function(a){var b=document.documentElement.scrollHeight-document.documentElement.clientHeight;
const c=b?document.documentElement.scrollTop/b:0;_ds.Tm(a.eventHandler,a,_ds.Gh,()=>{a.removeAttribute("animatable");a.background.removeAttribute("animatable");a.o.removeAttribute("animatable")});_ds.D(a,"animatable","");b=_ds.Fe(a.j`animatable`);b(a.background,"animatable","");b(a.o,"animatable","");a.hasAttribute("collapsed")?(_ds.D(a,"aria-expanded","true",a.Qb),_ds.D(a,"aria-label","Hide side navigation",a.Qb),_ds.D(a,"data-title","Hide side navigation",a.Qb),a.removeAttribute("collapsed"),RZ(a,
"Expanded book nav")):(a.Qb.removeAttribute("aria-expanded"),_ds.D(a,"aria-label","Show side navigation",a.Qb),_ds.D(a,"data-title","Show side navigation",a.Qb),_ds.D(a,"collapsed",""),RZ(a,"Collapsed book nav"));await _ds.Gl();b=document.documentElement.scrollHeight-document.documentElement.clientHeight;document.documentElement.scrollTop=Math.round(c*b)},KZ=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:b,label:"focus"===
b?"devsite-book-nav-filter input":"devsite-book-nav-filter filter-clear-button"},bubbles:!0}))},SZ=function(a){a.oa=Array.from(a.querySelectorAll(".devsite-mobile-nav-bottom .devsite-nav-list[menu=_book] .devsite-nav-item:not(.devsite-nav-heading)"))},UZ=function(a){const b=_ds.F().searchParams.get("nf");a.g&&b&&(a.g.value=b,TZ(a))},TZ=function(a){if(a.oa.length){LZ(a);MZ(a);var b,c,d=null==(b=a.g)?void 0:null==(c=b.value)?void 0:c.trim().toLowerCase();if(d){var e;null==(e=a.ma)||e.classList.remove("hidden");
for(const g of a.oa){c=g.querySelectorAll(".devsite-nav-text");b=g.classList.contains("devsite-nav-expandable");var f=e=!1;a=0;let h,k;if(d&&b&&(null==(h=g.querySelector(".devsite-nav-text"))?0:null==(k=h.textContent)?0:k.toLowerCase().includes(d)))f=e=!0;else for(const l of c){let m;d&&(null==(m=l.textContent)?0:m.toLowerCase().includes(d))&&(e=!0,++a)}if(!0===e){g.classList.remove("hidden");if(f){c=Array.from(g.querySelectorAll(".devsite-nav-item"));for(const l of c){l.classList.remove("hidden");
let m;d&&(null==(m=l.textContent)?0:m.toLowerCase().includes(d))&&++a}}c=void 0;(f=g.querySelector(".devsite-nav-text"))&&(e=null==(c=f.textContent)?void 0:c.replace(new RegExp(`(${d})`,"ig"),"<mark>$1</mark>"))&&_ds.De(f,_ds.We(e))}b&&0<a&&(b=g.querySelector(".devsite-nav-text"))&&(a=_ds.P(DZ,{Rw:a}),b.appendChild(a))}}else null==(f=a.ma)||f.classList.add("hidden")}},LZ=function(a){for(const b of a.oa){let c;b.classList.toggle("hidden",!(null==(c=a.g)||!c.value))}},MZ=function(a){if(a.querySelector("mark")){var b=
[...a.querySelectorAll(".devsite-nav-text > .devsite-nav-filter-match-count")];for(const c of b)c.remove();a=[...a.querySelectorAll(".devsite-nav-text > mark")];for(const c of a){a=c.parentElement;let d;b=null==(d=a)?void 0:d.textContent;a&&b&&_ds.De(a,_ds.We(b))}}},OZ=async function(a,b){if(a.v){var c=await _ds.v(),d=new _ds.dL,e=f=>{f=f.target;_ds.cL(d,f);a.ea.delete(f);c.unregisterIntersectionForElement(f)};for(const f of b)try{c.registerIntersectionForElement(f,e)}catch(g){e({target:f})}}},IZ=
function(a,b){let c=!1;if(a.h)for(const d of a.h.querySelectorAll("[menu]"))d.getAttribute("menu")===b?(d.removeAttribute("hidden"),c=!0):_ds.D(a,"hidden","",d);return c},VZ=function(a,b=a){b||(b=a);for(const c of b.querySelectorAll(".devsite-nav-active"))c.classList.remove("devsite-nav-active");a=_ds.Nl(_ds.F().pathname);a=`[href="${_ds.zl(a).href}"], [href="${a}"],
        [alt-paths~="${a}"]`;for(const c of b.querySelectorAll(a))c.classList.add("devsite-nav-active")},WZ=function(a,b=a){b||(b=a);if(a=b.querySelector(".devsite-mobile-nav-bottom"))for(a=a.querySelector(".devsite-nav-active");a&&a.parentElement&&a.parentElement!==b;)a.matches(".devsite-expandable-nav:not(.expanded)")&&a.classList.add("expanded"),a=a.parentElement},YZ=async function(a){a.v&&(a.removeAttribute("user-scrolled"),await _ds.Gl(),await XZ(a),await a.xa,await _ds.v(),await _ds.Gl(),await XZ(a))},
XZ=async function(a){if(a.v&&a.h){await _ds.v();var b=a.h.querySelector(".devsite-nav-active");b&&(a.hasAttribute("user-scrolled")||await ZZ(a,b))}},ZZ=async function(a,b){if(a.v){var c=a.hasAttribute("user-scrolled");a.scrollTop=_ds.gn(b,a,!0).y;await _ds.Gl();c&&_ds.D(a,"user-scrolled","")}},RZ=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:"click",label:b},bubbles:!0}))},$Z=class extends _ds.E{static get observedAttributes(){return["collapsed",
"fixed","hidden"]}constructor(){super();this.v=!1;this.ma=this.g=this.qa=this.h=null;this.oa=[];this.eventHandler=new _ds.G;this.ra=()=>{};this.ea=new Set;_ds.rj(this,this.j`animatable`,this.j`aria-expanded`,this.j`aria-label`,this.j`collapsed`,this.j`data-title`,this.j`fixed`,this.j`has-book-nav`,this.j`hidden`,this.j`top-level-nav`,this.j`user-scrolled`,this.j`visually-hidden`);this.background=document.createElement("div");this.background.classList.add("devsite-book-nav-bg");this.Qb=_ds.P(BZ);this.o=
_ds.P(CZ);this.xa=new Promise(a=>{this.ra=a});this.ua=new _ds.Qm(()=>{this.v&&FZ(this)},20);this.va=new _ds.Qm(()=>{TZ(this)},20)}async connectedCallback(){this.v=!0;_ds.rk(this.background,this);this.hasAttribute("hidden")&&(_ds.D(this,"hidden","",this.Qb),_ds.D(this,"hidden","",this.o));let a;null==(a=this.parentElement)||a.insertBefore(this.Qb,this.nextSibling);_ds.D(this,"aria-label","Hide side navigation",this.Qb);_ds.D(this,"data-title","Hide side navigation",this.Qb);_ds.D(this,"aria-expanded",
"true",this.Qb);let b;null==(b=this.parentElement)||b.insertBefore(this.o,this.nextSibling);if(this.qa=this.querySelector(".devsite-book-nav-filter"))this.g=this.qa.querySelector("input[type=text]"),this.ma=this.qa.querySelector(".filter-clear-button"),SZ(this),UZ(this);FZ(this);NZ(this);await this.init();PZ(this)}disconnectedCallback(){this.v=!1;_ds.I(this.eventHandler);QZ(this);this.ea.clear();var a=document.querySelector("#devsite-hamburger-menu");a&&_ds.D(this,"visually-hidden","",a);a=[this.background,
this.Qb,this.o];for(const b of a)b&&_ds.tk(b);this.removeAttribute("animatable");this.background.removeAttribute("animatable");this.o.removeAttribute("animatable");this.o.style.removeProperty("--devsite-js-book-nav-scrollbar-width")}attributeChangedCallback(a){"hidden"===a&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?"devsite-element-hidden":"devsite-element-visible",{bubbles:!0}));if("hidden"===a||"collapsed"===a){var b=document.querySelector(".devsite-main-content");b&&(this.hasAttribute("collapsed")||
this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):_ds.D(this,"has-book-nav","",b))}if("fixed"===a||"hidden"===a||"collapsed"===a){b=this.hasAttribute(a);const c=[this.background,this.Qb,this.o];for(const d of c)d&&(b?_ds.D(this,a,"",d):d.removeAttribute(a))}"fixed"===a&&this.ra()}async init(a=!0){if(this.v){this.o.style.setProperty("--devsite-js-book-nav-scrollbar-width",`${this.offsetWidth-this.clientWidth}px`);this.h=this.querySelector(".devsite-mobile-nav-bottom");_ds.D(this,"top-level-nav",
"");this.h&&this.h.querySelector("[menu=_book]")&&this.removeAttribute("top-level-nav");0===this.children.length&&_ds.D(this,"hidden","");if(this.background)for(const b of["hidden","fixed","animatable"])this.hasAttribute(b)&&_ds.D(this,b,"",this.background);!this.hasAttribute("hidden")&&a?(VZ(this),WZ(this),await YZ(this)):(await _ds.Gl(),await XZ(this))}}async Rb(a){a?(a=a.querySelector("nav")||null,VZ(this,a),WZ(this,a),a&&(await QZ(this),this.ea.clear(),PZ(this,a,!1)),_ds.tj(this,this.querySelector("nav"),
a)):_ds.qk(this);SZ(this);if(this.g){this.g.value="";let b;null==(b=this.ma)||b.classList.add("hidden");UZ(this)}await _ds.Gl();await this.init(!1)}};$Z.prototype.updateContent=$Z.prototype.Rb;$Z.prototype.attributeChangedCallback=$Z.prototype.attributeChangedCallback;$Z.prototype.disconnectedCallback=$Z.prototype.disconnectedCallback;$Z.prototype.connectedCallback=$Z.prototype.connectedCallback;try{customElements.define("devsite-book-nav",$Z)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookNav",a)};})(_ds_www);
