(function(_ds){var window=this;var jha=function(a){return(0,_ds.U)('<div class="devsite-popout" id="'+_ds.Y(a.id)+'"><div class="devsite-popout-result devsite-suggest-results-container" devsite-hide></div></div>')},X5=function(a){a="All results in "+_ds.X(a);return(0,_ds.U)('<button type="submit" class="button button-white devsite-search-project-scope" role="option">'+a+"</button>")},Y5=function(a,b,c){let d='<button type="submit" class="button button-white devsite-suggest-all-results" role="option">';b?(a="All results across "+
_ds.X(c),d+=a):(a='All results for "'+_ds.X(a)+'"',d+=a);return(0,_ds.U)(d+"</button>")},Z5=function(a,b,c,d,e,f,g,h){a=(c?"":'<devsite-analytics-scope action="'+_ds.Y(_ds.FI("Restricted "+d))+'">')+'<a class="devsite-result-item-link" href="'+_ds.Y(_ds.FI(a))+'" role="option"><span class="devsite-suggestion-fragment">'+_ds.X(b)+"</span>"+(h?'<span class="devsite-suggestion-fragment">'+_ds.X(h)+"</span>":"")+(e?'<span class="devsite-suggestion-fragment">'+_ds.X(e)+"</span>":"")+(f&&!g?'<span class="devsite-suggestion-fragment">'+
_ds.X(f)+"</span>":"");c||(a+='<span class="devsite-result-item-confidential">Confidential</span>');return(0,_ds.U)(a+("</a>"+(c?"":"</devsite-analytics-scope>")))},kha=function(a){var b=a.projectName;const c=a.Iq,d=a.query,e=a.Pq;a=a.Ek;b='<div class="devsite-suggest-wrapper '+(e?"":"devsite-search-disabled")+'"><div class="devsite-suggest-section"><div class="devsite-result-label">There are no suggestions for your query</div></div>'+((e?'<div class="devsite-suggest-footer">'+(c?X5(b):"")+Y5(d,c,
a)+"</div>":"")+"</div>");return(0,_ds.U)(b)},lha=function(a){var b=a.ix;const c=a.ux;var d=a.Dx;const e=a.projectName,f=a.Iq,g=a.query;var h=a.Ix;const k=a.Pq;a=a.Ek;let l;l='<div class="devsite-suggest-wrapper '+(k?"":"devsite-search-disabled")+'" tabindex="0" role="listbox" aria-label="'+_ds.uH("Search Suggestions");l+='"><div class="devsite-suggest-section">';if(0<d.length){l=l+'<div class="devsite-suggest-sub-section" role="group" aria-labelledby="devsite-suggest-header-partial-query"><div class="devsite-suggest-header" id="devsite-suggest-header-partial-query">Suggested searches'+
((f?'<span class="devsite-suggest-project">'+_ds.X(e)+"</span>":"")+'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" action="Query Suggestion Click">');var m=d.length;for(var n=0;n<m;n++){var q=d[n];l+='<div class="devsite-result-item devsite-nav-label" id="suggestion-partial-query-'+_ds.Y(n)+'" index=":'+_ds.Y(n)+'">'+Z5(q.getPath(),q.getTitle(),_ds.gh(q,14),"Query Suggestion Click")+"</div>"}l+="</devsite-analytics-scope></div>"}l+=0<d.length&&0<b.length?'<hr role="none">':
"";if(0<b.length){l=l+'<div class="devsite-suggest-sub-section" role="group" aria-labelledby="devsite-suggest-header-product"><div class="devsite-suggest-header" id="devsite-suggest-header-product">Pages'+((f?'<span class="devsite-suggest-project">'+_ds.X(e)+"</span>":"")+'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" action="Page Suggestion Click">');m=b.length;for(n=0;n<m;n++)q=b[n],l+='<div class="devsite-result-item devsite-nav-label" id="suggestion-product-'+
_ds.Y(n)+'" index=":'+_ds.Y(n)+'">'+Z5(q.getPath(),q.getTitle(),_ds.gh(q,14),"Page Suggestion Click",void 0,_ds.z(q,4),f)+"</div>";l+="</devsite-analytics-scope></div>"}l+=0<h.length&&0<b.length+d.length?'<hr role="none">':"";if(0<h.length){l=l+'<div class="devsite-suggest-sub-section" role="group" aria-labelledby="devsite-suggest-header-reference"><div class="devsite-suggest-header" id="devsite-suggest-header-reference">Reference'+((f?'<span class="devsite-suggest-project">'+_ds.X(e)+"</span>":"")+
'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" action="Reference Suggestion Click">');m=h.length;for(n=0;n<m;n++)q=h[n],l+='<div class="devsite-result-item devsite-nav-label" id="suggestion-reference-'+_ds.Y(n)+'" index=":'+_ds.Y(n)+'">'+Z5(q.getPath(),q.getTitle(),_ds.gh(q,14),"Reference Suggestion Click",_ds.z(q,3),_ds.z(q,4),f,_ds.dh(q,10,2)[0])+"</div>";l+="</devsite-analytics-scope></div>"}l+=0<c.length&&0<b.length+d.length+h.length?'<hr role="none">':"";if(0<
c.length){l+='<div class="devsite-suggest-sub-section" role="group" aria-labelledby="devsite-suggest-header-other-products"><div class="devsite-suggest-header" id="devsite-suggest-header-other-products">Products</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" action="Product Suggestion Click">';b=c.length;for(d=0;d<b;d++)h=c[d],l+='<div class="devsite-result-item devsite-nav-label" id="suggestion-other-products-'+_ds.Y(d)+'" index=":'+_ds.Y(d)+'">'+Z5(h.getPath(),h.getTitle(),
_ds.gh(h,14),"Product Suggestion Click")+"</div>";l+="</devsite-analytics-scope></div>"}l+="</div>"+(k?'<div class="devsite-suggest-footer" role="none">'+(f?X5(e):"")+Y5(g,f,a)+"</div>":"")+"</div>";return(0,_ds.U)(l)};var mha=/[ .()<>{}\[\]\/:,]+/,nha=0,qha=function(a){a.g&&(a.h.listen(a.g,"suggest-service-search",b=>{a:{var c=a.ma.querySelector(".highlight");if(c&&(c=c.querySelector(".devsite-result-item-link"))){c.click();break a}$5(a,b.detail.originalEvent,!!a.qa)}}),a.h.listen(a.g,"suggest-service-suggestions-received",b=>void oha(a,b)),a.h.listen(a.g,"suggest-service-focus",()=>{a6(a,"cloud-track-search-focus",null);a.ra=!0;b6(a,!0)}),a.h.listen(a.g,"suggest-service-blur",()=>{b6(a,!1)}),a.h.listen(a.g,"suggest-service-input",
()=>{!a.oa["Text Entered Into Search Bar"]&&a.g.query.trim()&&(a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",label:"Search",action:"Text Entered Into Search Bar"},bubbles:!0})),a.oa["Text Entered Into Search Bar"]=!0);a.ra&&(a6(a,"cloud-track-search-input",null),a.ra=!1)}),a.h.listen(a.g,"suggest-service-navigate",b=>void pha(a,b)),a.h.listen(document.body,"devsite-page-changed",()=>a.oa={}),_ds.xJ(a.g));a.v&&a.h.listen(a.v,"submit",b=>
{$5(a,b)});a.ma&&a.h.listen(a.ma,"click",b=>{const c=b.target;if(c.closest(".devsite-result-item-link")){b6(a,!1);let d;a6(a,"cloud-track-search-submit",{query:null==(d=a.o)?void 0:d.value,hG:c})}c.classList.contains("devsite-search-project-scope")&&$5(a,b,!0)});a.Aa&&a.h.listen(a.Aa,"click",()=>void b6(a,!0));a.xa&&a.h.listen(a.xa,"click",()=>void b6(a,!1))},oha=function(a,b){b=b.detail;var c=b.suggestions;b=b.query;if(a.g.query.toLowerCase().startsWith(b.toLowerCase()))if(c){var d=c.Md();c=d.filter(q=>
2===q.If());var e=d.filter(q=>3===q.If()),f=d.filter(q=>4===q.If()).slice(0,5),g=d.filter(q=>1===q.If());d=c.length+f.length+g.length;for(var h of f)h.setPath(_ds.zl(`${a.qa||"/s/results"}/?q=${h.getTitle()}`).toString());var k=b.split(mha);e.forEach(q=>_ds.QG(q,_ds.dh(q,10,2).filter(t=>k.some(w=>t.includes(w)))));h=a.getAttribute("project-name")||"";var l=a.hasAttribute("project-scope"),m=a.hasAttribute("enable-search"),n=a.getAttribute("tenant-name")||"";c={ix:c,projectName:h,Iq:l,ux:g,Dx:f,query:b,
Ix:e,Pq:m,Ek:n};0===d?_ds.O(a.ea,kha,c):(_ds.O(a.ea,lha,c),rha(a,b));a.o.setAttribute("aria-expanded","true");a.ea.removeAttribute("hidden")}else a.ea.setAttribute("hidden",""),a.o.setAttribute("aria-expanded","false")},a6=function(a,b,c=null){a.dispatchEvent(new CustomEvent(b,{detail:c,bubbles:!0}))},b6=function(a,b){if(a.va!==b){_ds.tJ(a.g,b);if(a.va=b)a.setAttribute("search-active","");else{let c=a.ma.querySelector(".highlight");c&&c.classList.remove("highlight");a.removeAttribute("search-active");
a.o.setAttribute("aria-expanded","false");_ds.qk(a.ea)}a.hasAttribute("capture")||a.dispatchEvent(new CustomEvent("devsite-search-toggle",{detail:{active:b},bubbles:!0}))}},pha=function(a,b){var c=b.detail;b=a.ea.querySelector(".highlight");let d;const e=Array.from(a.ea.querySelectorAll(".devsite-result-item"));let f=[];let g,h=-1;if(b){var k=_ds.Ik(b,l=>l.classList.contains("devsite-suggest-section"));f=Array.from(k.querySelectorAll(".devsite-result-item"));k=_ds.xk(b.parentNode.parentNode);g=_ds.yk(b.parentNode.parentNode);
h=e.indexOf(b)}switch(c.keyCode){case 37:if(!k&&!g)return;b&&(c=b.getAttribute("index"),g?(d=g.querySelector('[index="'+c+'"]'))||(d=_ds.$a(Array.from(g.querySelectorAll("[index]")))):k&&((d=k.querySelector('[index="'+c+'"]'))||(d=_ds.$a(Array.from(k.querySelectorAll("[index]"))))));break;case 39:if(!k&&!g)return;b&&(c=b.getAttribute("index"),k?(d=k.querySelector('[index="'+c+'"]'))||(d=_ds.$a(Array.from(k.querySelectorAll("[index]")))):g&&((d=g.querySelector('[index="'+c+'"]'))||(d=_ds.$a(Array.from(g.querySelectorAll("[index]"))))));
break;case 38:b?(d=e[h-1])||(d=_ds.$a(f)):d=_ds.$a(e);break;case 40:b?(d=e[h+1])||(d=f[0]):d=e[0]}b&&(b.classList.remove("highlight"),b.removeAttribute("aria-selected"));d&&(a.o.setAttribute("aria-activedescendant",d.id),d.setAttribute("aria-selected","true"),d.classList.add("highlight"),d.scrollIntoViewIfNeeded&&d.scrollIntoViewIfNeeded()||d.scrollIntoView())},$5=async function(a,b,c=!1){b.preventDefault();b.stopPropagation();if(a.hasAttribute("enable-search")){a.oa["Full Site Search"]||(a.dispatchEvent(new CustomEvent("devsite-analytics-observation",
{detail:{category:"Site-Wide Custom Events",label:"Search",action:"Full Site Search"},bubbles:!0})),a.oa["Full Site Search"]=!0);let d;a6(a,"cloud-track-search-submit",{query:null==(d=a.o)?void 0:d.value});b=c&&a.qa?_ds.zl(a.qa):_ds.zl(a.v.getAttribute("action"));c=new _ds.Sk(b.href);a.g.query&&_ds.el(c,"q",a.g.query);b.search=c.g.toString();await DevsiteApp.fetchPage(b.href,!a.hasAttribute("disable-history"));b6(a,!1)}},rha=function(a,b){b=new RegExp(`(${_ds.Uj(b)})`,"ig");a=a.ea.querySelectorAll(".devsite-suggestion-fragment");
for(const c of a)a=c.innerHTML,a=a.replace(b,"<b>$1</b>"),_ds.De(c,_ds.ej(a))},c6=class extends _ds.E{static get observedAttributes(){return["project-scope","url-scoped","disabled"]}constructor(){super();this.va=!1;this.oa={};this.ua="";this.qa=null;this.h=new _ds.G;this.g=null;this.ra=!1}disconnectedCallback(){_ds.I(this.h);this.g&&(this.g.dispose(),this.g=null)}attributeChangedCallback(a,b,c){switch(a){case "project-scope":this.ua=c||"";this.g&&(this.g.ra=this.ua);break;case "url-scoped":this.qa=
c;break;case "disabled":this.o&&(this.o.disabled=null!==c)}}connectedCallback(){if(this.v=this.querySelector("form")){this.o=this.v.querySelector(".devsite-search-query");this.Aa=this.v.querySelector(".devsite-search-button[search-open]");this.xa=this.querySelector(".devsite-search-button[search-close]");var a=`devsite-search-popout-container-id-${++nha}`;this.o.setAttribute("aria-controls",a);this.ma=_ds.P(jha,{id:a});this.ea=this.ma.querySelector(".devsite-suggest-results-container");this.v.appendChild(this.ma);
this.hasAttribute("project-scope")&&(this.ua=this.getAttribute("project-scope"));this.hasAttribute("url-scoped")&&(this.qa=this.getAttribute("url-scoped"));this.v&&this.o&&(this.g=new _ds.yJ(this,this.v,this.o),this.g.j=!0,this.g.Ca=this.hasAttribute("enable-query-completion"),this.g.ua=!0,this.g.Aa=!0,this.g.Fa=!0,this.g.ra=this.ua,this.g.j=this.hasAttribute("enable-suggestions"));qha(this)}}};c6.prototype.connectedCallback=c6.prototype.connectedCallback;c6.prototype.attributeChangedCallback=c6.prototype.attributeChangedCallback;
c6.prototype.disconnectedCallback=c6.prototype.disconnectedCallback;try{customElements.define("devsite-search",c6)}catch(a){console.warn("devsite.app.customElement.DevsiteSearch",a)};})(_ds_www);
