(function(_ds){var window=this;var Qia=function(a){const b=a.xo;let c='<div class="dropdown-tabbed-menu"><ul class="dropdown-tabbed-menu-list">';a=a.columns;const d=a.length;for(let e=0;e<d;e++){const f=a[e];c+='<li class="dropdown-tabbed-menu-list-item"><a href="#" column-id="'+_ds.Y(f.Xu)+'" tabindex="0" track-type="nav" track-name="'+_ds.Y(f.text)+'" track-metadata-eventdetail="#" track-metadata-position="nav - '+_ds.Y(b)+'" track-metadata-module="secondary nav">'+_ds.X(f.text)+"</a></li>"}return(0,_ds.U)(c+"</ul></div>")},
Ria=function(a){const b=a.xo,c=a.href;a=a.text;return(0,_ds.U)('<div class="dropdown-tabbed-menu-button"><a href="'+_ds.Y(_ds.FI(c))+'" track-type="nav" track-name="'+_ds.Y(a)+'" track-metadata-eventdetail="'+_ds.Y(c)+'" track-metadata-position="nav - '+_ds.Y(b)+'" track-metadata-module="secondary nav">'+_ds.X(a)+"</a></div>")};var Sia=function(a){a.Ac=Array.from(a.querySelectorAll("tab"));if(a.hasAttribute("data-is-tablist")){_ds.D(a,"role","tablist");var b;null==(b=a.Ac)||b.forEach(e=>{_ds.D(a,"role","tab",e)})}let c=a.querySelector(".devsite-tabs-wrapper");if(!c){c=a.ownerDocument.createElement("div");c.classList.add("devsite-tabs-wrapper");a.appendChild(c);var d;null==(d=a.Ac)||d.forEach(e=>{let f;null==(f=c)||f.appendChild(e)})}a.v=c;a.appendChild(c);a.hasAttribute("no-overflow")||(b=a.ownerDocument.createElement("tab"),
_ds.D(a,"overflow-tab","",b),a.hasAttribute("data-is-tablist")&&_ds.D(a,"role","tab",b),d=a.ownerDocument.createElement("a"),a.classList.contains("upper-tabs")?_ds.D(a,"aria-label","Extended Navigation",d):_ds.D(a,"aria-label","More Options",d),_ds.Be(d,_ds.xe("#")),d.textContent="More",d.classList.add("devsite-icon"),d.classList.add("devsite-icon-arrow-drop-down"),b.appendChild(d),a.g=b,d=a.ownerDocument.createElement("div"),d.classList.add("devsite-tabs-overflow-menu"),_ds.D(a,"scrollbars","",d),
_ds.D(a,"hidden","",d),a.o=d,b.appendChild(d),c.appendChild(b))},Via=function(a){let b;null==(b=a.Ac)||b.forEach(async(c,d)=>{if(await Tia(c)){var e=Array.from(c.querySelectorAll(".devsite-tabs-dropdown-column")),f=c.querySelector(".devsite-tabs-dropdown"),g=c.querySelector("a");e.forEach((h,k)=>{_ds.D(a,"column-id",`tab-${d}-column-${k}`,h)});e=e.map(h=>{const k=h.querySelector(".devsite-nav-title")||h.querySelector(".devsite-nav-item-title");return{Xu:h.getAttribute("column-id"),text:null==k?void 0:
k.textContent}});g&&(g=_ds.P(Qia,{xo:(g.textContent||"").toLowerCase().trim(),columns:e}),f&&(e=c.querySelector(".devsite-tabs-dropdown-content")))&&(f.insertBefore(g,e),f=c.querySelector(".dropdown-tabbed-menu a"),Uia(c),a.eventHandler.listen(g,"click",h=>{h.preventDefault();const k=c.querySelector(".dropdown-tabbed-menu-button");h=h.target;k&&h.tagName&&"a"===h.tagName.toLowerCase()&&!k.contains(h)&&Y6(a,c,(null==h?void 0:h.getAttribute("column-id"))||"")}),f&&Y6(a,c,f.getAttribute("column-id")||
""))}})},Z6=function(a,b){if(!b)return 0;const c=[];let d=b;for(;d.parentElement&&0===d.offsetWidth;)c.push(d),_ds.D(a,"render-hidden","",d),d=d.parentElement;a=_ds.jn(b).width;for(const e of c)e.removeAttribute("render-hidden");return a},Yia=function(a){a.eventHandler.listen(document.body,"devsite-sticky-resize",()=>{a.oa.Qa()});a.eventHandler.listen(a,"click",c=>{if(!(c.shiftKey||c.ctrlKey||c.metaKey||c.altKey)){var d=c.target,e=a.ea(d);if(e)if(e===a.g)$6(a,c);else if(a7(a),d.classList.contains("devsite-tabs-dropdown-toggle"))c.preventDefault(),
c.stopPropagation(),e.hasAttribute("dropdown--open")?b7(a):c7(a,e);else{var f;"A"===d.tagName?f=d:f=_ds.Jk(d,"A");var g=e.querySelector(".devsite-tabs-dropdown");g&&g.contains(d)?f&&f.hasAttribute("href")||(c.preventDefault(),c.stopPropagation()):(a.ua(e),f&&f&&"#"!==f.href||a.oa.Qa())}}});if(a.querySelector("tab[dropdown]")||a.querySelector("tab[overflow-tab]")){var b="onpointermove"in window?"pointerover":"mouseover";const c="onpointermove"in window?"pointerleave":"mouseleave",d=a.querySelectorAll("tab[clickable]");
if(d.length){for(const e of d)a.eventHandler.listen(e,"click",f=>{const g=f.target,h=a.ea(g),k=null==h?void 0:h.querySelector(".devsite-tabs-dropdown");if(k){let l;(null==(l=a.g)?0:l.contains(g))||k.contains(g)||(f.preventDefault(),f.stopPropagation(),(null==h?0:h.hasAttribute("dropdown--open"))?b7(a):d7(a,f))}});a.eventHandler.listen(document.body,"click",e=>{a.v&&!a.v.contains(e.target)&&b7(a)})}else a.eventHandler.listen(a,b,e=>void Wia(a,e)),a.eventHandler.listen(a,c,()=>void Xia(a))}b=[...a.querySelectorAll(".devsite-tabs-close-button")];
for(const c of b)a.eventHandler.listen(c,"click",()=>{b7(a)})},e7=function(a){a.g&&_ds.D(a,"hidden","",a.g);if(!(a.Ac&&3>a.Ac.length)){var b=Z6(a,a);if(0!==b){var c,d=(null==(c=a.Ac)?void 0:c.slice())||[],e=0,f;d.forEach(k=>{k.parentNode!==a.v&&(f?f.parentNode&&f.parentNode.insertBefore(k,f.nextSibling):_ds.sk(a.v,k,0));f=k;e+=Z6(a,k)});if(!(e<=b)){c=a.va;var g;null==(g=a.g)||g.removeAttribute("hidden");(g=a.querySelector("[active]"))&&(c+=Z6(a,g));for(var h;null==(h=d)?0:h.length;){const k=d.shift();
if(k===g)continue;const l=Z6(a,k||null);if(c+l<=b)c+=l;else{let m;null==(m=a.o)||m.appendChild(k)}}}}}},Wia=async function(a,b){(await _ds.v()).isTouchEnabled()||d7(a,b)},Xia=async function(a){(await _ds.v()).isTouchEnabled()||b7(a,300)},b7=function(a,b=0){_ds.I(a.h);window.clearTimeout(a.ma);a7(a);const c=a.querySelector("tab[dropdown--open]");if(c){const d=c.querySelector(".devsite-tabs-dropdown");d&&(_ds.D(a,"dropdown-transition","",d),_ds.Tm(a.h,d,_ds.Gh,()=>{d.removeAttribute("dropdown-transition");
a.removeAttribute("dropdown--open");_ds.D(a,"hidden","",d)}));a.ma=window.setTimeout(()=>{c.removeAttribute("dropdown--open");f7(a,c)},b)}else a.removeAttribute("dropdown--open")},d7=function(a,b){const c=b.target,d=a.ea(c);if(d){let e;d===a.g||(null==(e=a.g)?0:e.contains(c))?$6(a,b):c7(a,d)}},$6=async function(a,b){b.preventDefault();b.stopPropagation();b7(a);document.body.dispatchEvent(new CustomEvent("devsite-close-overflow-tabs"));await _ds.Gl();if(!a.hasAttribute("overflow-menu--open")){b=await _ds.v();
await b.whenReady();if(b.isTouchEnabled()){const d=e=>{a.contains(e.target)||a7(a);a.h.unlisten(document.body,["devsite-close-overflow-tabs","click"],d)};a.h.listen(document.body,["devsite-close-overflow-tabs","click"],d)}var c;null==(c=a.o)||c.removeAttribute("hidden");_ds.D(a,"overflow-menu--open","")}},c7=async function(a,b){a7(a);if(b.hasAttribute("dropdown")){if(_ds.I(a.h),window.clearTimeout(a.ma),!b.hasAttribute("dropdown--open")){(await _ds.v()).isTouchEnabled()&&_ds.Tm(a.h,document.body,
"click",g=>{a.contains(g.target)||b7(a)});var c=a.querySelector("tab[dropdown--open]"),d=b.querySelector(".devsite-tabs-dropdown");if(d){d.removeAttribute("hidden");_ds.Xm(d,"left","");_ds.Xm(d,"right","");var e=_ds.ik(window),f=Array.from(d.querySelectorAll(".devsite-tabs-dropdown-column"));if(!b.hasAttribute("dropdown-full")&&1<f.length){const g=[];f.forEach(k=>{g.push(k.scrollWidth)});const h=Math.max.apply(null,g);h*f.length<e.width?f.forEach(k=>{_ds.Xm(k,"width",`${h}px`)}):_ds.D(a,"dropdown-full",
"",b)}f=d.getBoundingClientRect();b.hasAttribute("dropdown-full")?Zia()?_ds.Xm(d,"right",`${f.x}px`):_ds.Xm(d,"left",`-${f.x}px`):(e=Math.min(f.left,f.left+f.width-e.width),0<e&&_ds.Xm(d,"left",`-${e}px`));c?(c.removeAttribute("dropdown--open"),f7(a,c),c=c.querySelector(".devsite-tabs-dropdown"),null==c||c.removeAttribute("dropdown-transition"),_ds.D(a,"hidden","",c)):(_ds.D(a,"dropdown-transition","",d),_ds.Tm(a.h,d,_ds.Gh,()=>{d.removeAttribute("dropdown-transition")}));window.requestAnimationFrame(()=>
{_ds.D(a,"dropdown--open","");_ds.D(a,"dropdown--open","",b);f7(a,b)})}else c&&(c.removeAttribute("dropdown--open"),f7(a,c))}}else b7(a)},a7=function(a){a.o&&_ds.D(a,"hidden","",a.o);a.removeAttribute("overflow-menu--open")},f7=function(a,b){const c=b.querySelector(".devsite-tabs-dropdown-toggle");b=b.hasAttribute("dropdown--open");c&&_ds.D(a,"aria-expanded",`${b}`,c)},Zia=function(){let a,b,c;return"rtl"===(null==(a=document)?void 0:null==(b=a.documentElement)?void 0:null==(c=b.getAttribute("dir"))?
void 0:c.toLowerCase())},Tia=async function(a){return(await _ds.v()).isTouchEnabled()||!a.hasAttribute("generated-tab-menu")?!1:!0},Uia=function(a){var b=a.querySelector(".dropdown-tabbed-menu-button-target");if(!a.querySelector(".dropdown-tabbed-menu-button")&&b){var c=a.querySelector("a");c&&(c=c.textContent,b=b.querySelector(".devsite-nav-item a"),a=a.querySelector(".dropdown-tabbed-menu"),b&&(c=_ds.P(Ria,{xo:(c||"").toLowerCase().trim(),href:b.getAttribute("href")||"",text:b.textContent||""}),
null==a||a.appendChild(c)))}},Y6=function(a,b,c){var d=Array.from(b.querySelectorAll(".devsite-tabs-dropdown-column"));b=Array.from(b.querySelectorAll(".dropdown-tabbed-menu a"));b.forEach(e=>{e.removeAttribute("active")});d.forEach(e=>{_ds.D(a,"hidden","",e)});b=b.find(e=>e.getAttribute("column-id")===c);d=d.find(e=>e.getAttribute("column-id")===c);b&&d&&(_ds.D(a,"active","",b),d.removeAttribute("hidden"))},g7=class extends _ds.E{constructor(){super();this.eventHandler=new _ds.G;this.h=new _ds.G;
this.oa=new _ds.Qm(()=>{e7(this)},20);this.ra=null;this.qa=!1;this.ma=0;this.o=this.g=null;this.va=0;this.Ac=[];this.v=null;_ds.rj(this,this.j`active`,this.j`aria-expanded`,this.j`aria-selected`,this.j`aria-label`,this.j`collapsed`,this.j`column-id`,this.j`connected`,this.j`data-is-tablist`,this.j`dropdown`,this.j`dropdown-full`,this.j`dropdown--open`,this.j`dropdown-transition`,this.j`hidden`,this.j`no-overflow`,this.j`overflow-menu--open`,this.j`overflow-tab`,this.j`render-hidden`,this.j`role`,
this.j`scrollbars`)}disconnectedCallback(){_ds.I(this.eventHandler);_ds.I(this.h)}connectedCallback(){this.qa||(Sia(this),this.qa=!0);_ds.D(this,"connected","");this.hasAttribute("no-overflow")||(this.g&&(_ds.D(this,"collapsed","",this.g),this.va=Z6(this,this.g),this.g.removeAttribute("collapsed")),Yia(this),e7(this));Via(this)}ea(a){for(;a&&a!==this;){if("TAB"===a.tagName.toUpperCase())return a;a=a.parentElement}return null}ua(a){const b=this.ra||this.querySelector("[active]");b&&(b.removeAttribute("active"),
_ds.D(this,"aria-selected","false",b));_ds.D(this,"active","",a);_ds.D(this,"aria-selected","true",a);this.ra=a}};g7.prototype.connectedCallback=g7.prototype.connectedCallback;g7.prototype.disconnectedCallback=g7.prototype.disconnectedCallback;try{customElements.define("devsite-tabs",g7)}catch(a){console.warn("devsite.app.customElement.DevsiteTabs",a)};})(_ds_www);
